### ISSUE TITLE
Thiếu "Miền Nam"

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#1]
Khi chọn địa bàn hoạt động cho chi đoàn thì chỉ có 3 phương án là: Miền Bắc, Miền Trung, Miền Tây Nam bộ. Như vậy còn thiếu phương án Miền Nam

**Comment by dukec2020** [comment]
Done

**Comment by lotuong** [comment]
A đã kiểm tra lại rồi. Thanks em! :)
