### ISSUE TITLE
Kiểm tra ràng buộc dữ liệu trước khi thực hiện xóa

### ISSUE THREAD

**Issue by dukec2020** [lotuong/ChamdiemHD#10]
Kiểm tra nếu dữ liệu có relation với table khác thì không cho xóa mà phải xóa dữ liệu ràng buộc ở table trước.

**Comment by lotuong** [comment]
Nghĩa là phải xoá hết các bản ghi chấm điểm rồi mới được xoá sự kiện đúng ko? :)

**Comment by dukec2020** [comment]
Vâng.

**Comment by dukec2020** [comment]
Em đã bổ sung tính năng: 
- Nếu là cấp đoàn cs trở xuống thì không cho xóa sự kiện nếu có dữ liệu ràng buộc.
- Nếu là admin thì cho xóa sk và xóa luôn tất cả ràng buộc.
