### ISSUE TITLE
Danh sách BCH Đoàn cơ sở bị lặp lại

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#11]
Giải pháp thành lập thêm 1 chi đoàn gọi là BCH Đoàn cơ sở giúp giải quyết được 1 số vấn đề: 
- giúp cho BCH theo dõi công việc thường xuyên không liên quan đến các chi đoàn
- giúp BCH đánh giá riêng hoạt động của các đ/c trong BCH
- giúp phân tách vai trò của 1 đ/c trong BCH với tư cách là đoàn viên và với tư cách là UV BCH Đoàn cơ sở
  Tuy nhiên cách này lại làm phát sinh 1 số hạn chế: 
- Số liệu thống kê tổng số đoàn viên sẽ không chính xác - thừa ra 15 đ/c
- Khó có cái nhìn tổng thể về hoạt động của 1 UV BCH trong một kỳ báo cáo
- "Chi đoàn" đặc biệt này không tương xứng với các chi đoàn còn lại nên nhìn bản danh sách không được đẹp mắt lắm

Không biết Công có cao kiến gì không?

**Comment by dukec2020** [comment]
Thực ra không cần phải tạo thêm anh ạ.
- Đối với việc chấm điểm UVBCH thì cũng có thể sử dụng itnhs năng chấm điểm cá nhân với sự kiện tham gia là các sk của Đoàn CS.
- Khi thống kê hoặc tổng hợp điểm của các đ/c này, hiện cũng có thể tìm theo cách thông thường qua các thông tin chi đoàn trực thuộc, tên. Ngoài ra nếu cần thì có thể bổ sung tính năng tìm kiếm theo chức danh, nó sẽ liệt kê ra các thông tin hoạt động của các đ/c này.

**Comment by lotuong** [comment]
Uh, cái này để tư duy thêm tí. Tạm thời kệ nó đã

**Comment by lotuong** [comment]
Đã nghĩ ra cách rồi em ơi

Vẫn cái database đấy thôi, nhưng phần CHỨC NĂNG cho anh thêm mục Sự kiện BCH Đoàn cơ sở và Theo dõi BCH Đoàn cơ sở. 
- Sự kiện BCH Đoàn cơ sở là các công việc được xử lý nội bộ trong BCH Đoàn cơ sở, không có sự tham gia của các chi đoàn. Nói cách khác đây là các sự kiện do "Chi đoàn BCH Đoàn cơ sở" làm đầu mối. Nhưng chi đoàn này sẽ không có đoàn viên. 
- Còn Theo dõi Đoàn cơ sở, thực chất là bảng theo dõi cá nhân. Nhưng có một số điểm khác sau: 
  --- Chỉ cho phép chọn Đoàn viên là Uỷ viên BCH, Uỷ viên Thường vụ, Bí thư, Phó bí thư Đoàn cơ sở và các trưởng ban, phó trưởng ban thuộc Đoàn cơ sở thôi. Hiện tại có 16 người thuộc diện này.
  --- Trong form đánh giá sẽ không cần nhập Chi đoàn nữa (Mặc định là Chi đoàn BCH Đoàn cơ sở) 
  --- Các sự kiện thì chỉ lấy từ Sự kiện BCH Đoàn cơ sở ra thôi (Sự kiện do Chi đoàn không quân BCH Đoàn cơ sở làm đầu mối) 

Phần này các account chi đoàn được xem nhưng không được thêm, bớt. UV BCH Đoàn cơ sở và các trưởng ban, phó ban được thêm bớt nhưng không được tự duyệt. Chỉ có Ban thường vụ trở lên được duyệt.

**Comment by lotuong** [comment]
Anh sẽ xoá hết đoàn viên của Chi đoàn BCH Đoàn cơ sở đi bây giờ. 
Có cách nào để ẩn cái chi đoàn này đi khi thống kê danh sách các chi đoàn không nhỉ?

**Comment by dukec2020** [comment]
Có anh, em sẽ thêm setting cho cái chi đoàn đặc biệt này.

On Sunday, July 14, 2013, lotuong wrote:

> Anh sẽ xoá hết đoàn viên của Chi đoàn BCH Đoàn cơ sở đi bây giờ.
> Có cách nào để ẩn cái chi đoàn này đi khi thống kê danh sách các chi đoàn
> không nhỉ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/11#issuecomment-20932641
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Trương hợp này em đang làm, nhưng gặp vấn đề hơi rắc rối, hiện giờ khi tạo 1 sự kiện, tùy theo user đó là đoàn cs hay là chi đoàn mà em gắn nó là sự kiện của đcs hay chi đoàn tương ứng, giờ thêm một cái sự kiện BCH nữa sẽ phát sinh mấy cái như sau:
- Cần bổ sung thêm quyền là UVBCH hoặc UVTV,... để tương ứng tạo sự kiện riêng cho BCH.
- Đối với các phân quyền, phải kiểm tra thêm cái quyền của 16 người này => khá nhiều chỗ phải kiểm tra.

Anh xem bố trí phương án khác cho đơn giản hơn thôi!

**Comment by dukec2020** [comment]
À, nếu mà gộp 2 form nhập và chấm điểm vào 1 thì chắc là sẽ có phương án đơn giản hơn, để em nc tiếp!
