### ISSUE TITLE
Sử dụng github

### ISSUE THREAD

**Issue by dukec2020** [lotuong/ChamdiemHD#12]
Cái này nó không cho phép chuyển trạng thái của issue anh nhỉ, và em tạo issue, cũng không add label được.
Cái này hình như gọi là bug tracker thì  không đúng lắm!
Em thì hay dùng redmine, tốt hơn nhiều.

**Comment by dukec2020** [comment]
Nếu tiện thì chuyển sang cái này, khá hay anh ạ:
http://www.hostedredmine.com/projects/qlhdd?jump=welcome

**Comment by lotuong** [comment]
Anh vào theo link của em nhưng không vào được do chưa được phân quyền. Em thử phân quyền cho anh vào ngó tí xem sao nhé. Nếu hay thì ta chuyển thôi. Nhưng đã trót lập ở đây rồi thì dùng cố nốt mấy hôm nữa cho hết cái milestone đầu tiên (tự rà soát) cũng được. 

Em có thể bấm nút Fork ở phía trên cùng bên tay phải để "ôm hết" cái dự án này sang tài khoản của em. Khi đó em sẽ có đủ quyền thay đổi label + chuyển trạng thái. Anh sẽ chạy qua làm việc bên đó.

**Comment by lotuong** [comment]
Anh đã thêm em là Collaborator rồi. Bây giờ chắc là chọn được label và chuyển trạng thái issue được. 
Ngoài ra còn tìm được nút Transfer để chuyển hết cho em quản lý dự án nữa (nếu cần). Anh làm collaborator thôi.

**Comment by dukec2020** [comment]
Em đã có quyền thêm label, nhưng cái này nó không có change status của 1 issue ngay cả với collaborator thì phải ?. Cái redmine anh tạo username là gì để em add anh thử ?

**Comment by lotuong** [comment]
Anh không chuyển quyền admin cho em được vì hệ thống báo là em cũng có 1 dự án cùng tên. Nếu em đã Fork cái repository của anh sang rồi thì đổi tên hoặc xoá nó đi để anh chuyển cái này sang nhé. 
Acc redmine của anh là manhphong. Em add thử xem nhé!

**Comment by dukec2020** [comment]
Ko cần nữa đau a, dùng của anh đc rồi. Cái redmine em tạo rồi đó, đã add anh.

**Comment by lotuong** [comment]
Anh vào xem rồi! :)
