### ISSUE TITLE
Hình ảnh trình bày trên header của trang web

### ISSUE THREAD

**Issue by dukec2020** [lotuong/ChamdiemHD#13]
Mình có nên cho ít hình ảnh hoạt động của Đoàn mình trên header cho nó phong phú không anh nhỉ?

**Comment by lotuong** [comment]
Đất ít quá nên anh nghĩ là chỉ nên đưa logo thôi. Tông màu được lựa chọn là vàng sáng với xanh đen. Để anh liên hệ với anh Thứ xin cái file logo nhé!

**Comment by dukec2020** [comment]
Ok a

On Sunday, July 14, 2013, lotuong wrote:

> Đất ít quá nên anh nghĩ là chỉ nên đưa logo thôi. Tông màu được lựa chọn
> là vàng sáng với xanh đen. Để anh liên hệ với anh Thứ xin cái file logo nhé!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/13#issuecomment-20932368
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Done, anh xem thành quả nhé :p
