### ISSUE TITLE
Thêm chức danh cán bộ đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#14]
Nhóm quản lý cấp cao của anh còn có thêm các chức danh như: Trưởng ban Văn nghệ, Trưởng ban Văn hoá, Phó ban Thể thao...

Thế nên em thêm giùm anh phần lựa chọn chức danh 2 mục là "Trưởng ban Đoàn CS" và "Phó ban Đoàn CS" nhé. Bỏ mục "Chức danh khác" đi.

**Comment by dukec2020** [comment]
Done
