### ISSUE TITLE
Vị trí nút tick chọn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#15]
Trong phần chấm điểm, ô tick chọn Vai trò và Kết quả nằm ở trước từ chỉ mức độ. Anh muốn chuyển ra sau cho đỡ nhầm lẫn. Ví dụ như phải là

VAI TRÒ: Tham gia ( )  Hỗ trợ ( )  Đầu mối ( )

thay vì hiện tại là

VAI TRÒ ( ) Tham gia ( ) Hỗ trợ ( ) Đầu mối

Tương tự với cái KẾT QUẢ

![chamdiem](https://f.cloud.github.com/assets/1740657/793915/ee25df2c-ec55-11e2-83fe-a12b4668cec6.png)

**Comment by lotuong** [comment]
Thêm nữa là bỏ mục Chưa Hoàn thành đi. Chỗ này bị thừa. Nếu Chưa hoàn thành thì sẽ bị Zero điểm. Như vậy các chi đoàn mất công nhập vào phần mềm chấm điểm làm gì? :smile_cat:

**Comment by dukec2020** [comment]
Mục chưa hoàn thành là giá trị mặc định, đâu cần phải chấm anh. Có nó thì mới có chỗ để giá trị mặc định, cũng không sao.
