### ISSUE TITLE
Tự động duyệt khi người có chức năng duyệt nhập điểm

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#16]
Em đặt chế độ Phê duyệt mặc định là "Chấp thuận" nếu người nhập điểm là Admin đấy à? Nếu user khác nhập thì nó sẽ ra là "Chưa duyệt" phải không? Tính năng này hay thiệt! Phân quyền cho Ban thường vụ nhé :+1:

**Comment by dukec2020** [comment]
Hiện tại em tạo user có 4 quyền: admin, đoàn cs, chi đoàn và đoàn viên. Đối với admin và ĐCS thì mặc định giá trị duyệt. Khi tạo user mới, a lấy quyền theo đó là được (các user BTV dùng quyền Đoàn CS luôn)
