### ISSUE TITLE
Phím tắt khi chọn tên chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#18]
Anh sửa tên của 1 số chi đoàn. Bỏ chữ "Ban" trong tên gọi đi. Như vậy vừa chuẩn hơn so với quyết định thành lập mà khi nhập số liệu lại nhanh hơn vì chỉ cần bấm chữ cái đầu tiên 1 - 2 lần!

**Comment by dukec2020** [comment]
Ok anh
