### ISSUE TITLE
Điều chỉnh một số giá trị mặc định

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#19]
Khi Đoàn cơ sở đánh giá theo thang điểm Xuất sắc, tốt, hoàn thành, chưa HT thì để giá trị mặc định là Tốt. Thông thường khi bị trừ điểm vì 1 lý do nào đó (chậm trễ chẳng hạn) thi mới để là hoàn thành.

Khi xem điểm các chi đoàn/cá nhân thì nên mặc định là xem điểm theo quý và xem tới quý hiện tại. Như vậy mọi người biết ngay được là kỳ tính điểm này chi đoàn mình đã được bao nhiêu điểm rồi.

**Comment by dukec2020** [comment]
Done!
