### ISSUE TITLE
Chậm phản ứng khi nhập thông tin

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#2]
Trong nhiều trường hợp, khi đặt trỏ chuột vào ô nhập text và bắt đầu gõ, khoảng 3 - 4 giấy sau chữ mới bắt đầu hiện ra.

**Comment by dukec2020** [comment]
Cái này có thể là do máy, a thử máy khác chưa? Nó liên quan tới client chứ không phải do server, vì website nó đâu có xử lý mấy user action này!!

**Comment by lotuong** [comment]
Lúc sau cũng không thấy bị như thế nữa. Có thể do server chập chờn!
