### ISSUE TITLE
Tăng giới hạn số dòng ở báo cáo chấm điểm

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#20]
Hiện tại giới hạn là 10 dòng. 
![page 1](https://f.cloud.github.com/assets/1740657/794171/ef231ec4-ec7a-11e2-8787-c23275dd0d41.png)

Nếu 1 chi đoàn có đúng 10 hoạt động thì sẽ phát sinh trang báo cáo thứ 2. Trang này trống và không có nút nào để quay trở lại trang đầu tiên.
![page 2](https://f.cloud.github.com/assets/1740657/794172/f4dbc85c-ec7a-11e2-89c6-85e2cd646a8a.png)

Theo kinh nghiệm của anh để giới hạn 25 dòng là vừa đẹp. Đủ để hiện hết bảng điểm của 1 quý trong 1 trang màn hình.

**Comment by lotuong** [comment]
Hình như Công xoá bản ghi mồ côi chưa hết nên điểm bị cộng sai mất rồi. Chỗ này cộng lại chỉ được 47 điểm chứ không phải 52.

**Comment by dukec2020** [comment]
Là do vấn đề hiển thị, tương tự cái issue liên quan. Done!
