### ISSUE TITLE
Lỗi cộng sai khi chấm điểm chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#21]
Theo như thống kê trong hình vẽ thì số điểm được cộng nhiều hơn số điểm thực tế:

Hình 1:
![page 3](https://f.cloud.github.com/assets/1740657/794175/7a6583aa-ec7b-11e2-8eeb-001efca1ba6f.png)

Hình 2:
![page 4](https://f.cloud.github.com/assets/1740657/794176/817047f2-ec7b-11e2-93ac-ecaa0dd21b7e.png)

**Comment by dukec2020** [comment]
Lỗi này do phần hiển thị nó có vấn đề, còn cộng vẫn đúng đó anh. Đã khắc phực bằng cách tăng lên 30 dòng /page.
