### ISSUE TITLE
Lỗi khi tạo sự kiện chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#22]
Khi tạo sự kiện chi đoàn thấy xuất hiện thông báo lỗi: 
![loi 404](https://f.cloud.github.com/assets/1740657/794469/1d76b2d0-ec9f-11e2-8ddc-d52077c993e3.png)

**Comment by dukec2020** [comment]
Em đang xử lý cái này nên nó bị lỗi đó anh, chờ chút em up cái mới lên.

**Comment by lotuong** [comment]
OK
