### ISSUE TITLE
Tạo drop-down list để xem điểm từng chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#23]
Mới có 30 chi đoàn thôi trông đã thế này rồi:
![list](https://f.cloud.github.com/assets/1740657/794524/08770cda-eca5-11e2-8789-053698070dec.png)
Có lẽ nên tạo mục chọn chi đoàn để xem điểm cho nó gọn bớt giao diện lại

**Comment by dukec2020** [comment]
Cái này em cũng tính rồi nhưng chưa nghĩ ra làm sao cho hợp lý. Nếu làm 
kiểu chọn thì nó sẽ không chạy nhanh được như hiện tại do phải gửi request.

**Comment by lotuong** [comment]
Ok, vay cu de do da :)
