### ISSUE TITLE
Tips trong gridview

### ISSUE THREAD

**Issue by dukec2020** [lotuong/ChamdiemHD#24]
![screen shot 2013-07-15 at 12 34 18 am](https://f.cloud.github.com/assets/172102/794603/89b4d48e-ecab-11e2-9e3d-e9ed2a2c4056.png)
Đối với gridview, những cột dữ liệu có link màu xanh nhạt là dữ liệu dạng inplace editor, anh có thể sửa trực tiếp bằng cách click vào link đó là được.
Đối với dữ liệu cột "Kích hoạt" thì có thể thao tác nhấn chuột để thay đổi trạng thái kích hoạt cho bản ghi.

**Comment by lotuong** [comment]
OK em!
Nhưng mà cái list sự kiện này có cột kích hoạt nào đâu? :)
