### ISSUE TITLE
Đề phòng rủi ro hoạt động

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#25]
Anh bị ám ảnh bới cái phần mềm này sao ý. Sáng nay mưa trời mát, chuông báo thức kêu xong đấm cho nó 1 phát rồi ngủ tiếp. Và thế là có 1 giấc mơ kinh dị: Em Công gọi điện bảo là cái laptop của em hỏng nên phần coding trang web đi hết rồi. Đang phải ngồi làm lại từ đầu. Hic, tự dưng đau lòng ko sao kể siết. Phải vội vã tỉnh dậy luôn.

Trước đó thì nghĩ cái label số 7 này không để làm gì. Vậy mà phải dùng đến thật. >_< Nhớ backup dữ liệu Công nhé!

**Comment by dukec2020** [comment]
Hehe, code em để trên svn, ko mất đc đâu anh!

On Monday, July 15, 2013, lotuong wrote:

> Anh bị ám ảnh bới cái phần mềm này sao ý. Sáng nay mưa trời mát, chuông
> báo thức kêu xong đấm cho nó 1 phát rồi ngủ tiếp. Và thế là có 1 giấc mơ
> kinh dị: Em Công gọi điện bảo là cái laptop của em hỏng nên phần coding
> trang web đi hết rồi. Đang phải ngồi làm lại từ đầu. Hic, tự dưng đau lòng
> ko sao kể siết. Phải vội vã tỉnh dậy luôn.
> 
> Trước đó thì nghĩ cái label số 7 này không để làm gì. Vậy mà phải dùng đến
> thật. >_< Nhớ backup dữ liệu Công nhé!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/25
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
