### ISSUE TITLE
Tham số vị trí trong bảng Loại sự kiện

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#26]
Trong bảng loại sự kiện, tham số "Vị trí" có tác dụng gì nhỉ?
Anh đoán là để điều chỉnh thứ tự các phần mục khi xuất báo cáo.
Nếu vậy thì ô trống trong gridview của nó đang quá bé để sửa, cần phải cho rộng ra tí nữa. 
Và giới hạn tham số vị trí từ 0 - 9 thôi vì chắc sẽ không có quá 10 mục điểm số đâu

**Comment by dukec2020** [comment]
Đúng là để dùng cho báo cáo đó anh. Cái này sẽ sắp theo thứ tự tăng dần,
nên cũng ko cần biết nó bằng bao nhiêu mà chỉ cần nó hơn thằng ở trước là
được, có chút lỗi nên chưa cho to ra được, em sẽ khắc phục sau!

2013/7/15 lotuong notifications@github.com

> Trong bảng loại sự kiện, tham số "Vị trí" có tác dụng gì nhỉ?
> Anh đoán là để điều chỉnh thứ tự các phần mục khi xuất báo cáo.
> Nếu vậy thì grid line view của nó đang quá bé để sửa, cần phải cho rộng ra
> tí nữa.
> Và giới hạn tham số vị trí từ 0 - 9 thôi vì chắc sẽ không có quá 10 mục
> điểm số đâu
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/26
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Done!
