### ISSUE TITLE
Mặc định loại sự kiện khi thêm mới Sự kiện Chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#27]
Khi các chi đoàn thêm mới sự kiện do mình tổ chức thì để mặc định loại sự kiện là HOẠT ĐỘNG RIÊNG CỦA CHI ĐOÀN

**Comment by dukec2020** [comment]
Done

**Comment by lotuong** [comment]
Cái này vẫn chưa được em nhé. Anh vẫn thấy mặc định là: "- Chọn phân loại -"
Nhưng mà cái này mức độ quan trọng thấp. Sửa được thì sửa cho nó hoàn hảo hơn thôi.

**Comment by dukec2020** [comment]
Chắc anh mới thay đổi dữ liệu phải không? Cái này em fix theo ID, khi ID
thay đổi thì nó bị sai đó mà, để em set lại là xong!

2013/7/17 lotuong notifications@github.com

> Cái này vẫn chưa được em nhé. Anh vẫn thấy mặc định là: "- Chọn phân loại
> -"
> Nhưng mà cái này mức độ quan trọng thấp. Sửa được thì sửa cho nó hoàn hảo
> hơn thôi.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/27#issuecomment-21119671
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Anh thấy lại được rồi! :)
