### ISSUE TITLE
Lỗi quản lý user

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#28]
Anh đăng nhập bằng tài khoản của chi đoàn CNTC vẫn xoá được tài khoản ngang cấp và cấp dưới (đoàn viên) của chi đoàn khác. Khi thử sửa (đổi tên) chi đoàn QTRR thì vẫn được. Tuy nhiên sau khi sửa xong thì QTRR trở thành đoàn viên của chi đoàn CNTC. Nói chung là ko thấy bị hạn chế gì hết! :dancers:

**Comment by dukec2020** [comment]
Ở mục người dùng ,em chưa thiết kế hoàn chỉnh!

2013/7/15 lotuong notifications@github.com

> Anh đăng nhập bằng tài khoản của chi đoàn CNTC vẫn xoá được tài khoản
> ngang cấp và cấp dưới (đoàn viên) của chi đoàn khác. Khi thử sửa (đổi tên)
> chi đoàn QTRR thì vẫn được. Tuy nhiên sau khi sửa xong thì QTRR trở thành
> đoàn viên của chi đoàn CNTC. Nói chung là ko thấy bị hạn chế gì hết! [image:
> :dancers:]
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/28
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Done!
