### ISSUE TITLE
Đơn vị của Chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#3]
Một số chi đoàn gồm đoàn viên đến từ 2 đơn vị. Ví dụ như: Ban Tổ chức Nhân sự và Ban Đào tạo. Trung tâm GD Hội sở và Ban Chiến lược... Nếu để gộp vào như hiện tại trong mục Đơn vị khi khai báo thông tin chi đoàn thì không phản ánh đúng được cơ cấu tổ chức của PVcombank

**Comment by lotuong** [comment]
Để đánh giá riêng Ban chấp hành Đoàn cơ sở anh đã tạo thêm 1 Chi đoàn nữa. Nhưng với "Chi đoàn" này không biết nên chọn Đơn vị là gì. Có lẽ mục Đơn vị nên để người dùng tự đánh vào chứ không cho chọn từ danh sách. Như thế đơn giản và tiện lợi hơn.

**Comment by dukec2020** [comment]
Nếu tự đánh, khi thống kê sẽ không được chặt chẽ các thông tin. Ví dụ khi gõ các tên giống nhau nhưng có dấu cách hoặc dấu chấm, thì nó sẽ bị phân biệt là khác nhau. Anh có thể tạo thêm đơn vị với tên là 2 ban trong trường hợp có 2 ban nhưng có 1 chi đoàn chẳng hạn (vì anh không cần quản lý tên đơn vị, nên đặt thế nào là do mình).
Với đoàn cơ sở, thì mình cũng tạo tên một đơn vị là đoàn cơ sở :)

**Comment by lotuong** [comment]
Đồng ý!
