### ISSUE TITLE
Không phân biệt chữ hoa chữ thường trong username

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#30]
hoặc là quy định username là bằng chữ thường hết, hoặc là không phân biệt chữ hoa chữ thường cho Username, nghĩa là username DAUTU thì viết là Dautu, DauTu hay dautu đều chấp nhận được. Như vậy đơn giản hoá rất nhiều cho việc nhớ cái account truy cập hệ thống của bà con!

**Comment by dukec2020** [comment]
Vậy em sẽ cho user về lower case hết nhé.
Khi nhập vào thì sẽ cho về lower case.
Khi tạo cũng lower case.
