### ISSUE TITLE
Lỗi khi phê duyệt điểm hoạt động của chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#31]
Sau khi Chi đoàn nhập sự kiện và tự chấm điểm, Đoàn cơ sở vào duyệt điểm nhưng ở phần gridview của sự kiện không hiện chữ "chưa duyệt" xanh, có gạch chân, mà lại là "Click để sửa" màu đen, không gạch chân. Khi click vào thì cho phép chọn các phương án chấp thuận, không chấp thuận... nhưng không lưu lại được kết quả chọn. Lần sau vào lại thấy "Click để sửa"
![loi phe duyet](https://f.cloud.github.com/assets/1740657/806041/45e3b99a-ee32-11e2-9011-3f5585eedd84.png)

**Comment by dukec2020** [comment]
Có thể user đó không có quyền duyệt đó anh, để em thử vào ktra coi sao.

2013/7/16 lotuong notifications@github.com

> Sau khi Chi đoàn nhập sự kiện và tự chấm điểm, Đoàn cơ sở vào duyệt điểm
> nhưng ở phần gridview của sự kiện không hiện chữ "chưa duyệt" xanh, có gạch
> chân, mà lại là "Click để sửa" màu đen, không gạch chân. Khi click vào thì
> cho phép chọn các phương án chấp thuận, không chấp thuận... nhưng không lưu
> lại được kết quả chọn. Lần sau vào lại thấy "Click để sửa"
> [image: loi phe duyet]https://f.cloud.github.com/assets/1740657/806041/45e3b99a-ee32-11e2-9011-3f5585eedd84.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/31
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Em đã sửa lỗi này!

2013/7/16 lotuong notifications@github.com

> Sau khi Chi đoàn nhập sự kiện và tự chấm điểm, Đoàn cơ sở vào duyệt điểm
> nhưng ở phần gridview của sự kiện không hiện chữ "chưa duyệt" xanh, có gạch
> chân, mà lại là "Click để sửa" màu đen, không gạch chân. Khi click vào thì
> cho phép chọn các phương án chấp thuận, không chấp thuận... nhưng không lưu
> lại được kết quả chọn. Lần sau vào lại thấy "Click để sửa"
> [image: loi phe duyet]https://f.cloud.github.com/assets/1740657/806041/45e3b99a-ee32-11e2-9011-3f5585eedd84.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/31
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
