### ISSUE TITLE
Thông báo sự kiện chưa duyệt

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#32]
Có cách nào để khi account pvfc (của đoàn cơ sở - có quyền duyệt sự kiện) đăng nhập thì góc trên màn hình của trang homepage hiện lên thông báo hiện có bao nhiêu sự kiện chưa được duyệt không em?

Như vậy để khi chi đoàn nhập sự kiện xong là đoàn cơ sở duyệt cho ra điểm số luôn. Nếu từ chối thì từ chối luôn, khỏi phải đợi lâu.

**Comment by dukec2020** [comment]
Được anh, cái này đơn giản mà!

2013/7/16 lotuong notifications@github.com

> Có cách nào để khi account pvfc (của đoàn cơ sở - có quyền duyệt sự kiện)
> đăng nhập thì góc trên màn hình của trang homepage hiện lên thông báo hiện
> có bao nhiêu sự kiện chưa được duyệt không em?
> 
> Như vậy để khi chi đoàn nhập sự kiện xong là đoàn cơ sở duyệt cho ra điểm
> số luôn. Nếu từ chối thì từ chối luôn, khỏi phải đợi lâu.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/32
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Em bổ sung vào rồi đó, cho vào cái menu bên trái luôn!

2013/7/16 Hoàng Văn Công hvcong@gmail.com

> Được anh, cái này đơn giản mà!
> 
> 2013/7/16 lotuong notifications@github.com
> 
> > Có cách nào để khi account pvfc (của đoàn cơ sở - có quyền duyệt sự kiện)
> > đăng nhập thì góc trên màn hình của trang homepage hiện lên thông báo hiện
> > có bao nhiêu sự kiện chưa được duyệt không em?
> > 
> > Như vậy để khi chi đoàn nhập sự kiện xong là đoàn cơ sở duyệt cho ra điểm
> > số luôn. Nếu từ chối thì từ chối luôn, khỏi phải đợi lâu.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/32
> > .
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage: http://www.absoft.com.vn
> 
> *
> *
> *

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
