### ISSUE TITLE
Đổi màu chữ "Chưa duyệt"

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#33]
Trong bảng theo dõi chi đoàn và theo dõi cá nhân, đổi màu chữ chưa duyệt sang màu khác, vd màu xanh đậm hơn để người duyệt dễ tìm kiếm và thực hiện việc cuyệt.

**Comment by dukec2020** [comment]
Cho thành 7 sắc cầu vồng luôn!
