### ISSUE TITLE
[NOTE] Phân quyền duyệt điểm đối với hoạt động của cá nhân

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#34]
Đoàn cơ sở không can thiệp vào việc "duyệt" điểm đối với cá nhân của các chi đoàn -> chấm xong là được luôn, không phải duyệt lại.
Đoàn cơ sở chấm điểm cho đoàn viên của các chi đoàn tham gia vào các chương chình do đoàn cơ sở tổ chức. Cũng chấm là xong luôn, không cần duyệt lại
Đoàn cơ sở chấm điểm đối với các uỷ viên BCH. Cũng chấm là xong luôn. Có thể điều chỉnh chứ không cần duyệt.

Tóm lại điểm cá nhân chấm phát xong luôn, không cần đến chức năng duyệt.

**Comment by dukec2020** [comment]
Done!

**Comment by lotuong** [comment]
Thế thì bỏ nốt cái này đi nữa nhé: 
![duyet ca nhan](https://f.cloud.github.com/assets/1740657/816710/e0a11a9c-ef52-11e2-8793-e0ed6d2bebae.PNG)
:smile:
