### ISSUE TITLE
Kết hợp nhập sự kiện chi đoàn và trình duyệt điểm trong cùng 1 form 

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#35]
Hiện tại chi đoàn nhập sự kiện xong sẽ phải tự vào phần theo dõi chi đoàn để chấm điểm và trình đoàn cơ sở duyệt. Sau đó còn phải chấm điểm cho từng đoàn viên đã tham gia sự kiện đó nữa. 

Để giảm bớt thao tác, có thể kết hợp việc Tạo sự kiện và chấm điểm 1 sự kiện của chi đoàn trên cùng 1 form. Làm được như vậy cũng sẽ hạn chế việc nhầm lẫn, quên sót, lặp lại sư kiện của các chi đoàn trong quá trình nhập dữ liệu. Tất nhiên là nếu họ cố ý làm sai thì vẫn chưa có cách nào để tự động hạn chế!

**Comment by dukec2020** [comment]
Ok, để em thiết kế xem.

2013/7/17 lotuong notifications@github.com

> Hiện tại chi đoàn nhập sự kiện xong sẽ phải tự vào phần theo dõi chi đoàn
> để chấm điểm và trình đoàn cơ sở duyệt. Sau đó còn phải chấm điểm cho từng
> đoàn viên đã tham gia sự kiện đó nữa.
> 
> Để giảm bớt thao tác, có thể kết hợp việc Tạo sự kiện và chấm điểm 1 sự
> kiện của chi đoàn trên cùng 1 form. Làm được như vậy cũng sẽ hạn chế việc
> nhầm lẫn, quên sót của các chi đoàn trong quá trình nhập dữ liệu.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/35
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Chà, em ngồi nghiên cứu phương án nhưng 2 cái chức năng này dữ liệu nó liên quan và phải có tuần tự, kết hợp nó rất là khó, chưa nghĩ ra kiểu gì cho hợp lý cả anh ạ.

**Comment by dukec2020** [comment]
Giữa sự kiện và chi đoan/cá nhân là quan hệ 1 nhiều, nếu muốn làm thao tác luôn thì chỉ có cách như sau:
- Khi tạo 1 sk, liệt kê luôn ds đoàn viên/ chi đoàn trong cùng 1 form, check chọn các đoàn viên, chi đoàn với các giá trị đánh giá mặc định. Khi nhấn tạo, thì dữ liẹu chấm điểm cho các chi đoàn/cá nhân cũng sẽ được tạo ra luôn. Anh thấy sao?

**Comment by dukec2020** [comment]
À, anh đang nói là chỉ với mình sk chi đoàn thôi phải không, nếu vậy thì em có phương án này:

Khi chi đoàn tạo SK, thì tạo luôn trình chấm điểm của chi đoàn.
CHo phép chọn luôn cá nhân trong danh sách để tạo chấm điểm cho cá nhân luôn.

**Comment by lotuong** [comment]
Cách này hay, 1 công được 3 việc luôn. Thử làm xem dư lào nhé! :smile:

**Comment by dukec2020** [comment]
Em đã làm xong, chi đoàn mặc định sẽ tự đệ trình tính điểm sk do mình tạo, cho phép chọn các đoàn viên trong chi đoàn mình tham gia sự kiện. Các tham số chấm điểm mặc định được sử dụng cho chi đoàn và đoàn viên khi tạo dữ liệu chấm này.
