### ISSUE TITLE
Làm thế nào để chấm điểm BCH Đoàn cơ sở

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#37]
Làm riêng 1 cái cho nó đỡ rối nhé:
Với mục tiêu CHẤM ĐIỂM CÁ NHÂN CÁC UỶ VIÊN BCH ĐOÀN CƠ SỞ, với thiết kế hiện tại của phần mềm, có thể làm như sau:
B1: Tạo sự kiện của Đoàn cơ sở
B2: Chấm điểm cho cá nhân tham gia vào sự kiện Đoàn cơ sở với cá nhân ở đây là các UV BCH.

Với cách này thì không phải chỉnh sửa gì thiết kế. Nhưng sẽ có 2 bất tiện:
KHÓ KHĂN 1: - Hàng tháng đoàn cơ sở xử lý rất nhiều việc mà không liên quan đến chi đoàn nào cả. Nếu để chung phần chấm điểm Các sự kiện Đoàn CS giao cho các chi đoàn với Các sự kiện Đoàn CS tự xử lý thì sẽ thành một khối to tướng. Khiến cho việc Theo dõi chi đoàn trở nên khó khăn, dễ sai, mất thời gian.  
KHÓ KHĂN 2: - Việc lựa chọn cá nhân uỷ viên BCH vào danh sách sẽ hơi mất thời gian do phải chọn chi đoàn, sau đó tìm trong số đoàn viên chi đoàn ai là uỷ viên BCH.

Để giải quyết KHÓ KHĂN 1: Tạo một "Chi đoàn" là Ban chấp hành Đoàn cơ sở. Chi đoàn này không có đoàn viên. Đối với các sự kiện của chi đoàn này thì không hạn chế chỉ chọn đoàn viên trong chi đoàn mà có thể chọn đoàn viên của chi đoàn khác. 

Để giải quyết KHÓ KHĂN 2: Sắp xếp đoàn viên trong chi đoàn theo cách ai chức cao hơn thì cho xếp trên đầu danh sách. Như vậy việc lựa chọn cá nhân để chấm điểm sẽ đỡ mất thời gian hơn. 

Cuối cùng, đặt thêm 1 mục trong CHỨC NĂNG là Sự kiện BCH Đoàn cơ sở. Chỉ để truy cập cho nhanh hơn, khỏi phải vào Sự kiện chi đoàn, sau đó chọn chi đoàn BCH Đoàn cơ sở thôi.

Em thử làm theo hướng này xem được không nhé!

**Comment by dukec2020** [comment]
Để em làm theo cách này, có vẻ thuận tiện hơn về mặt thiết kế.

**Comment by dukec2020** [comment]
Phát sinh trường hợp, cá nhân là UVBCH sẽ được tính điểm, khi đó chi đoàn đó sẽ có điểm cho cá nhân đó luôn anh nhỉ?

**Comment by dukec2020** [comment]
À, điểm cá nhân và chi đoàn là độc lập nhỉ, lẫn lộn hết cả :)

**Comment by lotuong** [comment]
UV BCH được tính điểm mà đến lúc muốn so sánh các ổng với nhau phải đi nhặt ở từng chi đoàn thì chết mệt. Làm giúp anh cái bộ lọc nữa zới! >_<

**Comment by dukec2020** [comment]
Em đã hoàn thiện tính năng này nhé, a test xem ok chưa
