### ISSUE TITLE
Tạm dừng thiết kế trong mấy ngày.

### ISSUE THREAD

**Issue by dukec2020** [lotuong/ChamdiemHD#38]
Hi anh,
Từ ngày 20-24/5 em đi du lịch nên sẽ không làm prj đc. Tạm thời nghỉ ngơi anh nhé.
Từ giờ đến mai em sẽ cố gắng bổ sung thêm các tính năng cần thiết (chấm điểm BCH, export excel).

**Comment by lotuong** [comment]
Công việc cũng ổn ổn rồi. Chỉ còn phần chấm điểm cá nhân và phần báo cáo là mình chưa soát tới. Cứ đi chơi vui vẻ đã. Ở nhà anh sẽ làm việc chăm chỉ thay phần của chú! :wink:

**Comment by lotuong** [comment]
Nhưng mà phải xong mấy phần để nhập liệu trước khi đi đấy nhé! :D
