### ISSUE TITLE
Chưa chọn được nhiều đoàn viên trong chi đoàn cùng tham gia 1 sự kiện

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#39]
Khi chi đoàn tạo 1 sự kiện, chỉ có 1 đoàn viên được chọn để tham gia sự kiện đó chứ chưa có cách nào chọn được nhiều hoặc tất cả đoàn viên.

**Comment by dukec2020** [comment]
Anh giữ ctrl để nhấn chon nhiều đv

On Tuesday, July 23, 2013, lotuong wrote:

> Khi chi đoàn tạo 1 sự kiện, chỉ có 1 đoàn viên được chọn để tham gia sự
> kiện đó chứ chưa có cách nào chọn được nhiều hoặc tất cả đoàn viên.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/39
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
OK, tốt rồi! :)
