### ISSUE TITLE
Chọn ngày sinh từ bảng lịch

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#4]
Chọn ngày sinh với ngày vào đoàn mà phải click click trên bảng lịch thì mỏi tay thấy ba má luôn. Có cách nào nhanh hơn không zậy? Mỗi lần click đi được có 1 tháng mà phải tua lại những 32 năm vị chi là phải ngồi click gần 400 lần. Lỡ làm nhầm là ốm với nhau luôn á!

**Comment by dukec2020** [comment]
Anh có thể gõ trực tiếp theo cú pháp: yyyy-mm-dd (năm-tháng-ngày) được mà. Em đã bổ sung tính năng chọn tháng/năm

**Comment by lotuong** [comment]
OK rồi. Chọn ngày tháng năm tốt! :+1:
