### ISSUE TITLE
Đoàn cơ sở nhập sự kiện thay cho chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#40]
Khi sử dụng Account của Đoàn cơ sở để tạo sự kiện thay cho chi đoàn Ba Tơ thì sự kiện đó không được đưa vào danh sách các sự kiện riêng của chi đoàn Ba Tơ (để tính điểm). Mặc dù trong danh sách sự kiện chi đoàn vẫn có! (VD: sự kiện Chương trình thi đua về đích sớm)

**Comment by dukec2020** [comment]
Để mấy hôm nữa e về ktra lại xem sao

On Tuesday, July 23, 2013, lotuong wrote:

> Khi sử dụng Account của Đoàn cơ sở để tạo sự kiện thay cho chi đoàn Ba Tơ
> thì sự kiện đó không được đưa vào danh sách các sự kiện mà chi đoàn Ba Tơ
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/40
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
uh, cứ bình tĩnh. Anh đang ngồi soát lỗi tiếp để chờ sẵn í mà! :)

**Comment by dukec2020** [comment]
Cái này em thử vẫn ok mà anh nhỉ,
em dùng user admin, tạo một sự kiến của ba tơ, sau đó vào ba tơ, nó vẫn
hiện lên của ba tơ mà?!

2013/7/23 lotuong notifications@github.com

> uh, cứ bình tĩnh. Anh đang ngồi soát lỗi tiếp để chờ sẵn í mà! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/40#issuecomment-21425128
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Nó hiện lên nhưng nó không chấm điểm. Em kiểm tra lại sự kiện có mã 89 của chi đoàn Ba Tơ. Mặc dù có trong danh sách sự kiện nhưng không có trong danh sách chấm điểm.

**Comment by dukec2020** [comment]
Là do khi đoàn cơ sở hoặc admin chấm điểm cho chi đoàn thì chỉ cho chọn các hoat động cấp trên Chi đoàn, em đã bổ sung thêm các hoạt động của chi đoàn, ko biết có đúng data follow ko?

**Comment by lotuong** [comment]
Anh thử dùng account PVFC để thử tạo sự kiện "Chương trình từ thiện tại Cát Hải" cho chi đoàn Trần Phú. Tạo sự kiện thì OK nhưng sang đến bước chấm điểm cho chi đoàn thì lại bị báo lỗi, không tạo được. 

Sử dụng account của chi đoàn Trần Phú vào xem thì nhìn thấy sự kiện rồi nhưng cũng không chấm điểm được (vì phần chấm điểm riêng cho sự kiện bị xoá mất rồi) :smiling_imp: 

Cần có tính năng này vì một số chi đoàn có hoạt động riêng nhưng lại lười không chịu báo cáo, nếu BCH Đoàn cơ sở nắm được thì có thể chủ động nhập và chấm điểm để chi đoàn khỏi thiệt thòi. Em xem lại giúp anh nhé.

À mà em đổi pass của account chi đoàn Trần Phú rồi à? Anh vào không được nên trong lúc ko nghĩ ra cách nào đã xoá mất cái account đó đi, thêm lại cái mới rồi. Dốt quá, lần sau chỉ cần tạo thêm 1 account chi đoàn & chọn chi đoàn Trần Phú là xong.

**Comment by dukec2020** [comment]
Có chút bug nhỏ, em đã fix, khi đoàn cs tạo xong có thể chấm cho chi đoàn.
