### ISSUE TITLE
Lỗi không hiện giá trị mặc định

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#41]
Khi các chi đoàn nhập sự kiện thì sự kiện đó tự động được chấm điểm theo các giá trị mặc định và trình đoàn cơ sở. Tuy nhiên giá trị này không hiển thị trong bảng duyệt điểm của Đoàn cơ sở, như hình minh hoạ phía dưới!
![loi1](https://f.cloud.github.com/assets/1740657/842814/d74940ce-f3b1-11e2-89f2-f3df0790747e.png)

**Comment by dukec2020** [comment]
Em test ko thấy bị nhỉ?

2013/7/23 lotuong notifications@github.com

> Khi các chi đoàn nhập sự kiện thì sự kiện đó tự động được chấm điểm theo
> các giá trị mặc định và trình đoàn cơ sở. Tuy nhiên giá trị này không hiển
> thị trong bảng duyệt điểm của Đoàn cơ sở, như hình minh hoạ phía dưới!
> [image: loi1]https://f.cloud.github.com/assets/1740657/842814/d74940ce-f3b1-11e2-89f2-f3df0790747e.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/41
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
À, đã thấy, và đã sửa!
