### ISSUE TITLE
Không phản hồi nếu không phải thẩm quyền

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#42]
Với quyền truy cập của chi đoàn, khi xem danh sách sự kiện của chi đoàn mình thì vẫn thấy các nút trạng thái: Chấp thuận, chưa duyệt... và khi click vào các trạng thái này thì vẫn hiện ra bảng chọn, mặc dù việc chọn là không lưu lại được. 

Có làm sao để nếu không được phân quyền duyệt thì khi click chuột vào link sẽ không có hành động nào xảy ra được không em?

**Comment by dukec2020** [comment]
Mặc dù họn đc nhưng ko có tác dụng gì đâu a. Để em ghiê cứu phưowng án tối
ưu hơn

On Tuesday, July 23, 2013, lotuong wrote:

> Với quyền truy cập của chi đoàn, khi xem danh sách sự kiện của chi đoàn
> mình thì vẫn thấy các nút trạng thái: Chấp thuận, chưa duyệt... và khi
> click vào các trạng thái này thì vẫn hiện ra bảng chọn, mặc dù việc chọn là
> không lưu lại được.
> 
> Có làm sao để nếu không được phân quyền duyệt thì khi click chuột vào link
> sẽ không có hành động nào xảy ra được không em?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/42
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
OK rồi!
