### ISSUE TITLE
Lấy ngày kết thúc theo ngày bắt đầu

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#43]
Trong quá trình nhập sự kiện thường ngày bắt đầu trùng với ngày kết thúc hoặc nếu là hoạt động kéo dài thì cũng chỉ trong vài ngày, nghĩa là vẫn trong tháng đó. Nếu trên form nhập liệu có thể lấy giá trị ngày bắt đầu làm giá trị ngày kết thúc mặc định thì sẽ rất tiện khi nhập liệu.

**Comment by dukec2020** [comment]
Em bổ sung tính năng, khi chọn ngày bắt đầu, thì ngày kết thúc gán bằng ngày bắt đầu luôn!
