### ISSUE TITLE
Phần ghi chú trong "Theo dõi cá nhân" chưa hoạt động

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#44]
Phần ghi chú trong "Theo dõi cá nhân" chưa hoạt động.
Bấm vào Thao tác "Edit" thì báo lỗi 403
![ghi chu](https://f.cloud.github.com/assets/1740657/846201/e5ea6884-f405-11e2-9f46-ff1d0a197a91.PNG)

**Comment by dukec2020** [comment]
Anh dùng user nào để duyệt, em thử dụng PVFC thì thấy duyệt ok mà anh? nhập ghi chú ngon lành!
