### ISSUE TITLE
Viết hướng dẫn sử dụng phần mềm

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#45]
Anh định viết hướng dấn sử dụng phần mềm trên word, chú ý làm link đến các phần mục khác nhau, sau đó convert qua .pdf để tránh bị thay đổi nội dung trước khi gửi cho các chi đoàn. Về việc này thì em có ý tưởng gì hay hơn không?

**Comment by lotuong** [comment]
Có thể đặt thêm mục Hỗ trợ trên menu chính ở cột bên trái được không nhỉ? Có độ 4 mục nhỏ, khi bấm vào sẽ hiện ra trang pop up hướng dẫn đối với từng phần: 
- Quản lý danh sách
- Quản lý sự kiện
- Chấm điểm sự kiện
- Xem và in báo cáo chám điểm
- Các câu hỏi thường gặp

Ngoài ra trong các form, ngay dưới đường dẫn menu có thể bổ sung thêm từ 3 - 6 dòng lưu ý đối với các thao tác trong form đó thì OK phải không em?

Như vậy thì không cần viết hướng dẫn gửi riêng nữa mà tích hợp vào phần mềm luôn.

**Comment by dukec2020** [comment]
Được anh ạ. A viết nội dung đi, rồi em cho vào.

On Friday, July 26, 2013, lotuong wrote:

> Có thể đặt thêm mục Hỗ trợ trên menu chính ở cột bên trái được không nhỉ?
> Có độ 4 mục nhỏ, khi bấm vào sẽ hiện ra trang pop up hướng dẫn đối với từng
> phần:
> - Quản lý danh sách
> - Quản lý sự kiện
> - Chấm điểm sự kiện
> - Xem và in báo cáo chám điểm
> 
> Ngoài ra trong các form, ngay dưới đường dẫn menu có thể bổ sung thêm từ 3
> - 6 dòng lưu ý đối với các thao tác trong form đó thì OK phải không em?
> 
> Như vậy thì không cần viết hướng dẫn gửi riêng nữa mà tích hợp vào phần
> mềm luôn.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/45#issuecomment-21600884
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Vậy anh viết ra File word rồi gửi qua email nhé!

**Comment by dukec2020** [comment]
Vâng

On Fri, Jul 26, 2013 at 11:08 PM, lotuong notifications@github.com wrote:

> Vậy anh viết ra File word rồi gửi qua email nhé!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/45#issuecomment-21630654
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Anh gửi file Các câu hỏi thường gặp qua email rồi nhé. Sau khi xem xét lại thì thấy các vấn đề cần hướng dẫn cũng không nhiều nên không cần phải chia ra thành nhiều mục nữa. Phần HỖ TRỢ chắc chỉ cần 2 mục là Các câu hỏi thường gặp và Thông tin liên hệ thôi. Em bổ sung thêm nhé. 

Phần đặt link đến từng câu hỏi của FAQ anh làm trên Word 2007 mãi không được, em xử lý giúp anh luôn với! >_<

**Comment by dukec2020** [comment]
Em đã đưa lên rồi, link a tạo xong ồi hả?

**Comment by lotuong** [comment]
Mấy cái đầu mục câu hỏi phông chữ hơi to Công ui. Cho nó tối đa bằng cái tiêu đề "CÁC CÂU HỎI THƯỜNG GẶP..." thôi!

**Comment by dukec2020** [comment]
Done
