### ISSUE TITLE
Bổ sung cột chức vụ trong danh sách đoàn viên

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#46]
Nhiều đoàn viên nắm giữ 2 chức vụ đoàn một lúc. Ví dụ:
Lê Ngọc Long: Trưởng ban Thể thao, Phó bí thư chi đoàn QTRR
Nguyễn Ngọc Bộ: UV BCH Đoàn CS - Bí thư chi đoàn Ba Tơ
Trần Mạnh PHong: Phó bí thư Đoàn CS - Trưởng ban Văn hoá

Có lẽ nên bổ sung 1 cột nữa để ghi chức vụ, trong đó cột thứ nhất ghi "Chức vụ Đoàn cao nhất", cột thứ 2 ghi "Chức danh khác"

**Comment by dukec2020** [comment]
Thêm cái này sẽ nảy sinh về vấn đề quyền hạn và chám điểm.
Có lẽ là em chỉ căn cứ vào chức vụ cao nhất thôi nhé, đỡ rườm rà, còn chức
vụ thứ 2 để xem thôi!

2013/7/24 lotuong notifications@github.com

> Nhiều đoàn viên nắm giữ 2 chức vụ đoàn một lúc. Ví dụ:
> Lê Ngọc Long: Trưởng ban Thể thao, Phó bí thư chi đoàn QTRR
> Nguyễn Ngọc Bộ: UV BCH - Bí thư chi đoàn Ba Tơ
> Trần Mạnh PHong: UV BTV - Trưởng ban Văn hoá
> 
> Có lẽ nên bổ sung 1 cột nữa để ghi chức vụ, trong đó cột thứ nhất ghi
> "Chức vụ Đoàn cao nhất", cột thứ 2 ghi "Chức danh khác"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/46
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Em đã làm theo hướng mô tả

**Comment by lotuong** [comment]
ừ, để xem thôi! :)

2013/7/25 hvcong notifications@github.com

> Thêm cái này sẽ nảy sinh về vấn đề quyền hạn và chám điểm.
> Có lẽ là em chỉ căn cứ vào chức vụ cao nhất thôi nhé, đỡ rườm rà, còn chức
> vụ thứ 2 để xem thôi!
> 
> 2013/7/24 lotuong notifications@github.com
> 
> > Nhiều đoàn viên nắm giữ 2 chức vụ đoàn một lúc. Ví dụ:
> > Lê Ngọc Long: Trưởng ban Thể thao, Phó bí thư chi đoàn QTRR
> > Nguyễn Ngọc Bộ: UV BCH - Bí thư chi đoàn Ba Tơ
> > Trần Mạnh PHong: UV BTV - Trưởng ban Văn hoá
> > 
> > Có lẽ nên bổ sung 1 cột nữa để ghi chức vụ, trong đó cột thứ nhất ghi
> > "Chức vụ Đoàn cao nhất", cột thứ 2 ghi "Chức danh khác"
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lotuong/ChamdiemHD/issues/46>
> > .
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage: http://www.absoft.com.vn
> 
> *
> *
> *
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/46#issuecomment-21531575
> .

## 

Manh Phong
manhphong@gmail.com
