### ISSUE TITLE
Phân loại đối với sự kiện của BCH Đoàn cơ sở

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#47]
Các sự kiện của BCH Đoàn cơ sở nên để mặc định trong mục "PHÂN LOẠI" là Sự kiện của BCH Đoàn cơ sở, hoặc là bỏ luôn mục này khỏi Form nhập liệu.

**Comment by dukec2020** [comment]
Chọn giá trị mặc định cho phân loại thì phải có giá trị và gán giá trị cho nó, em sẽ tạo SK này và đưa vào cấu hình hệ thống nhé.

**Comment by dukec2020** [comment]
Em đã bổ sung tính năng này, tuy nhiên, cũng giống như chi đoàn, khi xóa phân loại đi thì phải điều chỉnh lại giá trị này!
