### ISSUE TITLE
Không xoá được sự kiện của Đoàn cơ sở

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#48]
Sao anh không xoá được 2 sự kiện test của em nhỉ?

Thấy báo lỗi 403 không cho phép xoá vì còn dữ liệu liên quan. Trong trường hợp này là dữ liệu nào vậy?
![undelete](https://f.cloud.github.com/assets/1740657/849684/fda48a14-f477-11e2-8072-50964cb94957.png)

**Comment by dukec2020** [comment]
Nó liên quan tới mấy sk của cá nhân bch đó anh

On Wednesday, July 24, 2013, lotuong wrote:

> Sao anh không xoá được 2 sự kiện test của em nhỉ?
> 
> Thấy báo lỗi 403 không cho phép xoá vì còn dữ liệu liên quan. Trong trường
> hợp này là dữ liệu nào vậy?
> [image: undelete]https://f.cloud.github.com/assets/1740657/849684/fda48a14-f477-11e2-8072-50964cb94957.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/48
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
À à, ra là ko xoá được thằng bố vì thằng con sẽ mồ côi. :)
