### ISSUE TITLE
Nhập liên tiếp nhiều sự kiện của BCH Đoàn cơ sở

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#49]
Khi nhập xong 1 sự kiện của BCH Đoàn cơ sở và bấm nút Tạo mới, bảng tóm tắt chi tiết sự kiện vừa nhập sẽ hiện ra. Phía trên hiện các nút cho phép người dùng xem danh sách/ Xoá/ Sửa/ Thêm sự kiện. 

Khi click vào nút Thêm sự kiện thì lại hiện ra form thêm sự kiện của Chi đoàn chứ không phải Form thêm sự kiện của BCH Đoàn cơ sở.

**Comment by dukec2020** [comment]
Cái này em chưa xử lý, vì giữa các loại sự kiện khác nhau (của BCH, chi
đoàn, cá nhân), nếu nhấn tạo mới theo từng bước từ ngoài vào trong thì ok,
còn tạo từ các chức năng bên trong thì mặc định sẽ là tạo cho chi đoàn.

2013/7/26 lotuong notifications@github.com

> Khi nhập xong 1 sự kiện của BCH Đoàn cơ sở và bấm nút Tạo mới, bảng tóm
> tắt chi tiết sự kiện vừa nhập sẽ hiện ra. Phía trên hiện các nút cho phép
> người dùng xem danh sách/ Xoá/ Sửa/ Thêm sự kiện.
> 
> Khi click vào nút Thêm sự kiện thì lại hiện ra form thêm sự kiện của Chi
> đoàn chứ không phải Form thêm sự kiện của BCH Đoàn cơ sở.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/49
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
OK, cứ tạm vậy đã, hi vọng sau này có cách nào đó để khắc phục.

**Comment by lotuong** [comment]
Đã vậy ẩn bớt cái nút đó đi để người dùng khỏi bấm vào! :)

**Comment by dukec2020** [comment]
Done
