### ISSUE TITLE
Đếm số bản ghi thoả mãn điều kiện lọc

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#5]
Chức năng lọc danh sách đoàn viên rất hay. Có thể giúp lọc ra tất cả các đoàn viên trong 1 chi đoàn. Tuy nhiên có cách nào để khi áp dụng 1 điều kiện lọc nào đó thì hệ thống tự đếm số bản ghi thoả mãn điều kiện và ghi thành 1 dòng ở phía dưới cùng không? 

Ví dụ khi lọc các đoàn viên của chi đoàn "BCH Đoàn cơ sở" thì ở dưới hiện ra: Có 16 bản ghi thoả mãn điều kiện.

**Comment by dukec2020** [comment]
Được anh, để em bổ sung. Em đang làm cái tính năng thống kê tổng hợp ở trang chủ nữa, sẽ đưa lên sớm.

**Comment by dukec2020** [comment]
Done
