### ISSUE TITLE
Sắp xêp danh sách sự kiện theo thời gian

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#50]
Đối với danh sách sự kiện Đoàn cơ sở, nên sắp xếp theo thứ tự Ngày bắt đầu. Sự kiện mới hơn thì đưa lên trên. 

Các danh sách sự kiện khác cũng nên sắp xếp như vậy.

**Comment by dukec2020** [comment]
Ý anh là sx chỗ nào nhỉ? trong danh sách grid hay là trong các combobox? trong grid, anh có thể sx bằng cách nhấn vào column header.

**Comment by dukec2020** [comment]
Done
