### ISSUE TITLE
Bỏ phần thừa trong form Theo dõi chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#52]
Bỏ phần trong khung màu đỏ để tránh một sự kiện bị chấm điểm 2 lần
![tdcd](https://f.cloud.github.com/assets/1740657/863978/c39f0d94-f616-11e2-9ca4-3a76d01447c9.png)

**Comment by dukec2020** [comment]
Bỏ đi thì thêm sao được anh?

On Sat, Jul 27, 2013 at 12:14 AM, lotuong notifications@github.com wrote:

> Bỏ phần trong khung màu đỏ để tránh một sự kiện bị chấm điểm 2 lần
> [image: tdcd]https://f.cloud.github.com/assets/1740657/863978/c39f0d94-f616-11e2-9ca4-3a76d01447c9.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/52
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Thì khi thêm sự kiện thì đã kèm luôn chấm điểm rồi mà. Lúc sau chỉ vào để
chỉnh lại điểm thôi!

**Comment by lotuong** [comment]
À, chỉ bỏ nếu người sử dụng là chi đoàn thôi. Nếu người sử dụng là Đoàn cơ sở thì không bỏ được

**Comment by dukec2020** [comment]
Done
