### ISSUE TITLE
Sửa form thêm mới người dùng

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#54]
Hiện tại account ở cấp chi đoàn chỉ có thể thêm mới người dùng là đoàn viên. Phân quyền như vậy cũng tốt, đảm bảo Đoàn cơ sở quản lý được các account cấp chi đoàn. Nhưng trong form thêm người dùng ở cấp chi đoàn có một chỗ cần sửa lại cho đúng: Là account cấp Đoàn viên chứ không phải cấp Chi đoàn
![nd](https://f.cloud.github.com/assets/1740657/864189/2d54f276-f61c-11e2-9db6-a0f49a5cea25.png)

**Comment by dukec2020** [comment]
Done
