### ISSUE TITLE
Danh mục báo cáo excel

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#55]
1. BÁO CÁO hoạt động của một chi đoàn chia theo Loại sự kiện trong một thời kỳ (Chọn: tháng, quý, năm)
2. BÁO CÁO thành tích của một cá nhân trong một thời kỳ (Chọn: tháng, quý, năm)
3. BẢNG ĐIỂM thi đua của các chi đoàn sắp xếp từ cao xuống thấp trong một thời kỳ (Chọn: tháng, quý, năm)
4. BẢNG ĐIỂM thi đua cá nhân theo chi đoàn (Tên, ngày sinh, giới tính) kèm theo điểm thi đua trong kỳ (tháng, quý, năm)
5. DANH SÁCH đoàn viên theo chi đoàn - Thống kê dữ liệu chi tiết nhất có thể, có dòng tổng cộng cuối mỗi chi đoàn và tổng cộng của toàn Đoàn cơ sở.
   6BÁO CÁO hoạt động của Đoàn cơ sở chia theo Mảng hoạt động trong một thời kỳ (Chọn: tháng, quý, năm)

**Comment by dukec2020** [comment]
Anh đã dùng svn bao giờ chưa?
Hiện tại tài liệu và mã nguồn dự án em quản lý thông qua subversion, nếu
anh biết dùng svn thì em sẽ gửi link của svn để anh checkout và update
thông tin khi cần?

2013/7/28 lotuong notifications@github.com

> 1. Báo cáo hoạt động của một chi đoàn chia theo Mảng hoạt động trong
>    một thời kỳ (Chọn: tháng, quý, năm)
> 2. Báo cáo thành tích của một cá nhân trong một thời kỳ (Chọn: tháng,
>    quý, năm)
> 3. Bảng điểm thi đua của các chi đoàn sắp xếp từ cao xuống thấp trong
>    một thời kỳ (Chọn: tháng, quý, năm)
> 4. Danh sách đoàn viên theo chi đoàn (Tên, ngày sinh, giới tính) kèm
>    theo điểm thi đua trong kỳ (tháng, quý, năm)
> 5. Danh sách đoàn viên theo chi đoàn - Thống kê dữ liệu chi tiết nhất
>    có thể, có dòng tổng cộng ở dưới cùng.
> 6. Thống kê số liệu đoàn viên theo mẫu báo cáo tập đoàn (Mẫu này anh
>    sẽ cung cấp sau)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/55
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Kiến thức lập trình của anh mới chỉ dừng ở có tí kinh nghiệm về Access 2000 thôi nên không dám động vào mã nguồn đâu. Còn nếu để edit phần hướng dẫn sử dụng thì anh làm được. Em cứ gửi link để anh nghiên cứu xem ntn!

**Comment by dukec2020** [comment]
Ý em là trong đó có cả tài liệu và src, anh chỉ đưa tài liệu vào đó cho
tiện thôi.

link svn: http://123.26.249.194:8080/svn/201306.QLDV/
Anh download tortoisesvn về nhé,
Nó có các thao tác: checkout, update, commit, resolve conflict,...

User: phongtm
pass :

2013/7/29 lotuong notifications@github.com

> Kiến thức lập trình của anh mới chỉ dừng ở có tí kinh nghiệm về Access
> 2000 thôi nên không dám động vào mã nguồn đâu. Còn nếu để edit phần hướng
> dẫn sử dụng thì anh làm được. Em cứ gửi link để anh nghiên cứu xem ntn!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/55#issuecomment-21696382
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Về yêu cầu format của file excel, có yêu cầu gì nhiều ko anh? vì nếu để export thành một file chuẩn định dạng e hơi khó, export thành dạng dữ liệu thô thì ok.

**Comment by lotuong** [comment]
Tối thiểu phải có tiêu đề báo cáo + kỳ báo cáo. Với các cột thì phải có tiêu đề cột và độ rộng mỗi cột đủ để thể hiện thông tin. Nếu cố định độ rộng của cột được là tốt nhất để xuất báo cáo ra có thể in luôn, không phải căn lại trang.

Yêu cầu cao hơn nữa thì có thêm phần tiêu ngữ như sau:
          ĐOÀN TNCS HỒ CHÍ MINH
TẬP ĐOÀN DẦU KHÍ QUỐC GIA VIỆT NAM
                 BAN CHÂP HÀNH 
NGÂN HÀNG TMCP ĐẠI CHÚNG VIỆT NAM                                             Hà Nội, ngày.... tháng.... năm....

Còn nếu chưa làm được ngay thì xuất dữ liệu thô cũng được.

**Comment by dukec2020** [comment]
Mấy cái này thì chắc ok anh ạ.

2013/7/29 lotuong notifications@github.com

> Tối thiểu phải có tiêu đề báo cáo + kỳ báo cáo. Với các cột thì phải có
> tiêu đề cột và độ rộng mỗi cột đủ để thể hiện thông tin.
> 
> Yêu cầu cao hơn nữa thì có thêm phần tiêu ngữ như sau:
> ĐOÀN TNCS HỒ CHÍ MINH
> TẬP ĐOÀN DẦU KHÍ QUỐC GIA VIỆT NAM
> BAN CHÂP HÀNH
> NGÂN HÀNG TMCP ĐẠI CHÚNG VIỆT NAM Hà Nội, ngày.... tháng.... năm....
> 
> Còn nếu chưa làm được ngay thì xuất dữ liệu thô cũng được.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/55#issuecomment-21698334
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Nếu có mẫu báo cáo nào a gửi cho em nhé, em đỡ phải ngồi tạo mẫu.
Em đã tìm ra giải pháp dùng template, nhưng template đơn giản chút thì mới được.

**Comment by lotuong** [comment]
Để anh tạo mẫu cho. Rồi đưa lên SVN nhé!

**Comment by dukec2020** [comment]
Báo cáo đầu tiên đã ra lò, mời anh xem tại: http://thanhnien.pvcombank.vn/index.php/ranking/branchAction

Mẫu báo cáo a xem trong svn: D:\Documents\prj\website\201306.QLDV\05.Development\QLDV\protected\views\reports

**Comment by dukec2020** [comment]
Khi tạo báo cáo này sẽ phát sinh một số vấn đề liên quan tới chuẩn đặt tên chi đoàn, định dạng tên chi đoàn để hiển thị:

Ví dụ: tên chi đoàn phải bỏ "Chi đoàn" ở đầu, VD: "Chi đoàn Trần Phú" => "Trần Phú"
Tên chi đoàn hiện tại là chữ thường, khi export ra nó bị sai định dạng, nên chăng làm một trường viết hoa, chỉ phục vụ báo cáo. Vì neeus convert bawngf code, nhiều khi nó vẫn bị lệch font, VD: Trần Phú => uppercase(Trần Phú) => TRần PHÚ

**Comment by dukec2020** [comment]
- Đã bổ sung báo cáo hoạt động cá nhân.

Làm cái báo cáo này lâu thật :(

**Comment by lotuong** [comment]
Hôm nay họp hành nhiều quá. Bây giờ anh mới bắt đầu làm được! :(
Vấn đề tiêu ngữ phức tạp quá, chắc không cần đâu. Vì mấy cái báo cáo này cũng chỉ gửi để biết chứ không mấy khi phải in ra đóng dấu gửi đi.

Anh làm một loạt mẫu rồi gửi qua mail cho em nhé. Vì anh không đưa file lên svn được.

**Comment by lotuong** [comment]
Hình như còn có mấy công cụ làm báo cáo kiểu như Crystal report gì đó. Em đã dùng bao giờ chưa?

**Comment by dukec2020** [comment]
Cái đó là cho dotnet anh ạ, cái em đang làm là PHP.

**Comment by dukec2020** [comment]
Em mới bổ sung report báo cáo hoạt động chi đoàn theo mẫu mới, a test xem có ok ko nhé.

**Comment by dukec2020** [comment]
Hi anh, có cái mẫu báo cáo hoạt động đoàn cơ sở, nó lấy dữ liệu gì anh nhỉ? các sự kiện của đoàn cơ sở, hay là chỉ những sự kiện mà BCH tham gia?

**Comment by lotuong** [comment]
Báo cáo hoạt động đoàn cơ sở gồm Sự kiện Đoàn cơ sở + sự kiện chi đoàn. Không bao gồm sự kiện BCH Đoàn cơ sở.

**Comment by dukec2020** [comment]
Done.
