### ISSUE TITLE
Viết tài liệu về yêu cầu tối thiểu của browser khi dùng ứng dụng

### ISSUE THREAD

**Issue by dukec2020** [lotuong/ChamdiemHD#57]
Browser phải hỗ trợ HTML5, tối thiểu là các tag: canvas, rgba, font-face
Khuyên dùng: Chrome, Firefox >10, IE>=8, Safari 4

**Comment by lotuong** [comment]
Anh sẽ đưa phần này vào hướng dẫn sử dụng gửi tới các chi đoàn

**Comment by dukec2020** [comment]
Bỏ quách IE đi anh ạ, bắt dùng FF, chrome hoặc safari.
