### ISSUE TITLE
Thêm ghi chú cho các tính năng

### ISSUE THREAD

**Issue by dukec2020** [lotuong/ChamdiemHD#58]
Lấy từ yêu cầu trong mail (file xls) về các ghi chú, chỉ dẫn khi sử dụng ứng dụng.

**Comment by dukec2020** [comment]
Các yêu cầu em tổ chức lại chút, có cái em để dạng ghi chú ở form, có cái em cho vào tiêu đề, có cái em lại để dạng alert message - ẩn sau 5s.

**Comment by lotuong** [comment]
OK em!
