### ISSUE TITLE
Theo dõi khen thưởng

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#59]
Cần bổ sung tính năng này để ghi lại các danh hiệu mà một tập thể/cá nhân đạt được. Chẳng hạn muốn biết Chi đoàn X/Đoàn cơ sở/Cá nhân Y đã đạt được các thành tích gì, được khen thưởng danh hiệu gì, được giải thưởng gì từ trước tới giờ (hoặc chọn trong một khoảng thời gian nhất định) thì phần mềm có thể thống kê và báo cáo được. 

Em nghiên cứu xem có cách nào không nhé

**Comment by dukec2020** [comment]
Nếu nhập vào rồi thống kê thì ko cí gì anh. Lấy dữ liệu đã có và xử lý mới
khó.

**Comment by lotuong** [comment]
Nhập vào rồi thống kê thôi. Cần 1 cái form riêng để nhập. Nối với cá nhân hoặc chi đoàn. Cả 1 list các danh hiệu nữa. Cá nhân có Đoàn viên xuất sắc, Đoàn viên Tiêu biểu, Đoàn viên tiên tiến. Chi đoàn cũng có chi đoàn xuất sắc, chi đoàn tiêu biểu, chi đoàn tiên tiến. Danh hiệu này thì ghi nhận mỗi năm 1 lần. 

Còn nhiều danh hiệu khác nữa thì một lúc nhớ không hết. Để lúc nào phát sinh thì bổ sung vào list vậy.

**Comment by dukec2020** [comment]
Done
