### ISSUE TITLE
Nút kích hoạt trong trang sự kiện

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#6]
Một sự kiện được kích hoạt có ý nghĩa gì và có ảnh hưởng đến chức năng nào khác của phần mềm không?

**Comment by dukec2020** [comment]
Thuộc tính kích hoặt sẽ cho phép sử dụng thông tin đó hay không, nên nếu không kích hoạt một cái thì khả năng sẽ ảnh hưởng đến các cái liên quan khác.

**Comment by lotuong** [comment]
Để thử xem ntn!

**Comment by lotuong** [comment]
Đúng rồi, khi hết quý hoặc sau khi tổng kết một sự kiện, Đoàn cơ sở sẽ tắt kích hoạt sự kiện để các chi đoàn hết cơ hội ghi thêm điểm vào sự kiện mà mình bỏ qua, không tham gia.

**Comment by dukec2020** [comment]
Nếu đúng ra thì khi có ràng buộc dữ liệu, nếu cha mà bị đóng thì con cũng bị đóng, nhưng như vậy nó loằng ngoằng quá. Hiện tại em chỉ quan tâm đến cấp hiện tại, ví dụ khi lấy danh sách sự kiện để chấm, thì em kiểm tra sự kiện đó có đang kích hoạt hay không, nếu không thì không lấy, và như vậy nó đang phù hợp với yc của anh :)

**Comment by lotuong** [comment]
Anh đang lo là đến quý sau khi Đoàn cơ sở ngồi chấm điểm cho các chi đoàn đã tham gia hoạt động do mình làm đầu mối sẽ rất mệt vì phải chọn Sự kiện từ một danh sách quá lớn, tích cóp từ các quý trước lại. Cần có cách nào đó để khi chấm điểm hàng quý thì các sự kiện chỉ được lấy trong phạm vi 1 quý trước đó thôi thì mới được.

**Comment by dukec2020** [comment]
Cái này đơn giản mà anh. Hiện tại em đang cho nó sắp xếp theo ngày tạo, 
nên cái mới sẽ ở đầu sanh sách chọn, cũng tiện thôi anh!
Còn nếu cần thiết thì ẩn luôn cái cũ đi!

**Comment by lotuong** [comment]
Có trường hợp nào 1 chi đoàn được chấm điểm 2 lần cho cùng 1 sự kiện ko
nhỉ? Phải phòng ngừa trc chuyện đó. Còn sự kiện cũ ẩn đi đc là tốt nhất.

**Comment by dukec2020** [comment]
Có anh ạ, cái này chưa kiểm soát đc. Em cũng xử lý mà chưa đc.

**Comment by lotuong** [comment]
Đóng để mở một issue khác
