### ISSUE TITLE
Báo cáo hoạt động chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#60]
1. Sửa menu từ Danh sách thành Báo cáo cho nó đúng bản chất.
2. Xoá bớt các sheet thừa, chỉ để lại sheet 1
3. Trong trường hợp chi đoàn không có hoạt động nào trong kỳ báo cáo thì phải có thông báo nào đó hoặc là in ra báo cáo trống (không có mấy cái mở đóng ngoặc { } )

**Comment by lotuong** [comment]
Báo cáo hiện các đoàn viên có trạng thái kích hoạt là True nhưng khi đếm số đoàn viên trong chi đoàn thì lại đếm cả những đoàn viên có trạng thái kích hoạt là False. Dẫn đến số liệu về tổng số đoàn viên không chính xác!

**Comment by dukec2020** [comment]
Chưa tái hiện được cái lỗi hiện mấy cái dấu {}, anh cho em một ví dụ dữ liệu đầu vào đi.

**Comment by lotuong** [comment]
Đây 
![bc chi doan cntc](https://f.cloud.github.com/assets/1740657/914112/32050fd6-fe2d-11e2-9c03-7dc7095f2cb2.png)

và đây nữa em nhé
![bc doan co so](https://f.cloud.github.com/assets/1740657/914115/435782f0-fe2d-11e2-9216-f42d73dfb3b4.png)

**Comment by dukec2020** [comment]
Done.

On Tue, Aug 6, 2013 at 7:15 AM, lotuong notifications@github.com wrote:

> Đây
> [image: bc chi doan cntc]https://f.cloud.github.com/assets/1740657/914112/32050fd6-fe2d-11e2-9c03-7dc7095f2cb2.png
> 
> và đây nữa em nhé
> [image: bc doan co so]https://f.cloud.github.com/assets/1740657/914115/435782f0-fe2d-11e2-9216-f42d73dfb3b4.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/60#issuecomment-22150293
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
