### ISSUE TITLE
Báo cáo hoạt động cá nhân

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#61]
1. Để phân biệt với báo cáo các danh hiệu đạt được (báo cáo thành tích cá nhân) thì nên đổi tên báo cáo này là Báo cáo hoạt động cá nhân cả ở trong file excel và menu. 
2. Bỏ bớt các sheet thừa
3. Chỗ hiện ngày lập báo cáo chưa chạy, cần sửa lại

**Comment by dukec2020** [comment]
Done
