### ISSUE TITLE
Mặc định bộ lọc theo chi đoàn khi xem danh sách đoàn viên

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#62]
Khi truy cập bằng account của chi đoàn và bấm vào Danh sách đoàn viên thì sẽ thấy danh sách toàn bộ đoàn viên của Đoàn cơ sở. (Các tiêu chí lọc chưa được nhập)

Nên đổi thành nếu chi đoàn nào đăng nhập vào thì hiện danh sách đoàn viên của chi đoàn đó. Họ có thể thay đổi tiêu chí lọc để xem danh sách đoàn viên của chi đoàn khác hoặc của toàn bộ Đoàn cơ sở.

**Comment by dukec2020** [comment]
Done
