### ISSUE TITLE
Đổi tên các báo cáo trong mục Báo cáo hoạt động chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#64]
Đổi tên các loại báo cáo để dễ phân biệt
Báo cáo thành tích -> Bảng điểm tổng hợp
BC Hoạt động chi đoàn -> Bảng điểm chi đoàn
BC Tổng hợp -> Báo cáo hoạt động Đoàn CS

**Comment by dukec2020** [comment]
Done
