### ISSUE TITLE
Thiết kế lại mẫu BC Hoạt động chi đoàn (Bảng điểm chi đoàn)

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#65]
Mục đích của báo cáo này là các chi đoàn thấy được mình đã kiếm được bao nhiêu điểm thi đua trong kỳ, từ những hoạt động nào. Vì vậy cần thực hiện các sửa đổi sau:
- Không cho phép in báo cáo này nếu không chọn một chi đoàn cụ thể. 
- Đối với mỗi hoạt động thì hiện điểm thi đua kèm theo và Tổng điểm ở dưới cùng.

**Comment by dukec2020** [comment]
Ý anh là sao nhỉ? cái báo cáo này, hiện tại nếu chi đoàn ko chọn mã chi đoànthì nó sẽ mặc định giá trị option là "Báo cáo hoạt động Đoàn CS" dù cho có chọn "Bảng điểm chi đoàn" hay không.
Giờ a muốn cái follow này nó rõ hơn, chọn "Bảng điểm chi đoàn" thì phải chọn mã chi đoàn hay sạo anh?

Cái  điểm của từng hoạt động sẽ cho vào cột kết quả anh nhỉ?

**Comment by lotuong** [comment]
Đúng rồi. Cái báo cáo này Đoàn cơ sở không cần. Mà là các chi đoàn cần để rà soát lại mình đã được chấm điểm ở những hoạt động nào, tổng cộng là bn thôi.

**Comment by dukec2020** [comment]
Done
