### ISSUE TITLE
Thiết kế lại mẫu BC Tổng hợp (BC hoạt động Đoàn CS)

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#66]
Đây là báo cáo tổng hợp của Đoàn cơ sở, vì vậy cần phân chia các sự kiện theo MẢNG HOẠT ĐỘNG chứ không theo LOẠI SỰ KIỆN.
Có lẽ nên cho cột Kết quả trong báo cáo rộng ra một chút để đảm bảo hiện đủ các nội dung mô tả sự kiện liên quan.

**Comment by dukec2020** [comment]
Trước là theo loại sự kiện anh nhỉ, vì có thiết kế loại sự kiện có trường thứ tự.
Giờ sang mảng hoạt động: (văn hóa, văn nghệ)...? thì em sẽ phải thêm trường này vào!

**Comment by lotuong** [comment]
OK em!

**Comment by dukec2020** [comment]
Phát sinh một vấn đề, đó là cái report nó sẽ lấy các dữ liệu mà có gán mảng
hoạt động, đối với dữ liệu ko có mảng hoạt động sẽ phát sih vấn đề. Liệu dữ
liệu có hoàn toàn được gán thông tin mảng hoạt động không anh, hoặc nếu
không có thì cũng phải cho nó một cái mảng hoạt động mặc định, vd: "Không
phân loại"

On Thu, Aug 15, 2013 at 4:31 PM, lotuong notifications@github.com wrote:

> OK em!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-22693409
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
À, em ktra dữ liệu thì thấy có đủ ồi, nhưng để tránh trường hợp người
dùng không set, em sẽ ràng buộc cái này là bắt buộc phải chọn anh nhé.

**Comment by lotuong** [comment]
OK! :)

**Comment by lotuong** [comment]
Báo cáo này vẫn chưa được Công ơi. Các mục Thể thao nó cứ rời nhau ra chứ chưa tập trung được vào một chỗ!

**Comment by dukec2020** [comment]
Là như thế nào anh nhỉ? anh gửi file đính kèm em xem nhé.

2013/8/21 lotuong notifications@github.com

> Báo cáo này vẫn chưa được Công ơi. Các mục Thể thao nó cứ rời nhau ra chứ
> chưa tập trung được vào một chỗ!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-23025112
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Anh gửi mẫu vào mail công ty rồi đấy! :)

**Comment by dukec2020** [comment]
Anh thử ktra lại xem được chưa nhé, hình như được rồi :), chỉ cần set order
cho các phân loại hoạt động là đuwọc anh ạ.

2013/8/26 lotuong notifications@github.com

> Anh gửi mẫu vào mail công ty rồi đấy! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-23248903
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Sửa thêm 1 chút xíu nữa Công ơi: Sau khi chia theo các mảng văn hoá - thể thao rồi thì ưu tiên xếp thứ tự theo tên sự kiện chứ không xếp thứ tự theo tên chi đoàn. 
:)

**Comment by lotuong** [comment]
KHẨN: Hôm nay lôi ra dùng thử mới tá hoả là báo cáo Hoạt động Đoàn cơ sở chỉ gồm hoạt động của các chi đoàn chứ chưa bao gồm hoạt động của BCH Đoàn cơ sở (Phần Sự kiện Đoàn CS)
Em sửa giúp anh sớm nhé. Đến lúc phải làm báo cáo cả năm rồi!!!

**Comment by dukec2020** [comment]
ok anh.

2013/9/25 lotuong notifications@github.com

> KHẨN: Hôm nay lôi ra dùng thử mới tá hoả là báo cáo Hoạt động Đoàn cơ sở
> chỉ gồm hoạt động của các chi đoàn chứ chưa bao gồm hoạt động của BCH Đoàn
> cơ sở (Phần Sự kiện Đoàn CS)
> Em sửa giúp anh sớm nhé. Đến lúc phải làm báo cáo cả năm rồi!!!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-25058676
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Hi anh,
Em xem lại thì thấy thế này:
Các dữ liệu ở phần báo cáo hiện nay là các sự kiện và có đánh giá.
Các sự kiện đoàn cơ sở là các sự kiện chưa có đánh giá,
Nếu tích hợp 2 cái này thì sẽ có vấn đề phát sinh là dữ liệu đánh giá đó
anh.
Còn nếu chỉ thống kê thì nó lại ko phải là báo cáo hoạt động, mà nó là báo
cáo danh mục các sự kiện.!

2013/9/25 Hoàng Văn Công hvcong@gmail.com

> ok anh.
> 
> 2013/9/25 lotuong notifications@github.com
> 
> > KHẨN: Hôm nay lôi ra dùng thử mới tá hoả là báo cáo Hoạt động Đoàn cơ sở
> > chỉ gồm hoạt động của các chi đoàn chứ chưa bao gồm hoạt động của BCH Đoàn
> > cơ sở (Phần Sự kiện Đoàn CS)
> > Em sửa giúp anh sớm nhé. Đến lúc phải làm báo cáo cả năm rồi!!!
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-25058676
> > .
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage: http://www.absoft.com.vn
> 
> *
> *
> *

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Hiện tại báo cáo này gồm các mục: 
STT - HOẠT ĐỘNG - CHI ĐOÀN - NGÀY BẮT ĐẦU - NGÀY KẾT THÚC - KẾT QUẢ
Đối với các hoạt động thì nhóm lại thành các nhóm: Văn hoá, Thể thao, Văn nghệ, GD Chính trị tư tưởng...
Trong các nhóm này lại sắp xếp theo tên các hoạt động, để các chi đoàn cùng tham gia vào một hoạt động do Đoàn cơ sở chỉ đạo triển khai thì được gộp lại với nhau. 

Mục đích thiết kế như vậy để thuận tiện trong việc làm báo cáo 6 tháng, báo cáo cả năm của Đoàn cơ sở - sẽ đối chiếu báo cáo từ phần mềm để xem có hoạt động nào mình báo cáo thiếu không. Vì vậy mà không cần thông tin về đánh giá hoạt động. 

Còn tên báo cáo thì đổi lại thành Danh sách các sự kiện cũng được.

**Comment by dukec2020** [comment]
Vậy thì có sự thay đổi đó anh, trước đây em lấy dữ liêu ở phần đánh giá,
giờ sẽ lấy dữ liệu ở phần sự kiện (không có thông tin đánh giá liên quan).
Nếu ko vấn đề gì thì em sẽ điều chỉnh lại như vậy.

2013/9/26 lotuong notifications@github.com

> Hiện tại báo cáo này gồm các mục:
> STT - HOẠT ĐỘNG - CHI ĐOÀN - NGÀY BẮT ĐẦU - NGÀY KẾT THÚC - KẾT QUẢ
> Đối với các hoạt động thì nhóm lại thành các nhóm: Văn hoá, Thể thao, Văn
> nghệ, GD Chính trị tư tưởng...
> Trong các nhóm này lại sắp xếp theo tên các hoạt động, để các chi đoàn
> cùng tham gia vào một hoạt động do Đoàn cơ sở chỉ đạo triển khai thì được
> gộp lại với nhau.
> 
> Mục đích thiết kế như vậy để thuận tiện trong việc làm báo cáo 6 tháng,
> báo cáo cả năm của Đoàn cơ sở - sẽ đối chiếu báo cáo từ phần mềm để xem có
> hoạt động nào mình báo cáo thiếu không. Vì vậy mà không cần thông tin về
> đánh giá hoạt động.
> 
> Còn tên báo cáo thì đổi lại thành Danh sách các sự kiện cũng được.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-25146729
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
OK, em điều chỉnh lại xem sao nhé! :)

**Comment by dukec2020** [comment]
Chà, nghĩ mãi mà chưa thấy ổn anh ạ, trong báo cáo này có thông tin chi
đoàn, thông tin này lưu ở dữ liệu đánh giá (task), nếu chỉ lấy event thì ko
lấy được thông tin chi đoàn! Vậy với các sự kiện đoàn cơ sở, cũng phải chấm
cho chi đoàn thì nó mới hiện lên được!

2013/9/26 lotuong notifications@github.com

> OK, em điều chỉnh lại xem sao nhé! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-25147174
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Ví dụ một hoạt động của đoàn cơ sở là "hỗ trợ sinh nhật tháng 9", em vừa
chấm thử cho Trần Phú, thì nó hiện lên đủ ngay, anh xem thử nhé.
Ok thì xóa đi giúp em  :)

2013/9/27 Hoàng Văn Công hvcong@gmail.com

> Chà, nghĩ mãi mà chưa thấy ổn anh ạ, trong báo cáo này có thông tin chi
> đoàn, thông tin này lưu ở dữ liệu đánh giá (task), nếu chỉ lấy event thì ko
> lấy được thông tin chi đoàn! Vậy với các sự kiện đoàn cơ sở, cũng phải chấm
> cho chi đoàn thì nó mới hiện lên được!
> 
> 2013/9/26 lotuong notifications@github.com
> 
> > OK, em điều chỉnh lại xem sao nhé! :)
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/66#issuecomment-25147174
> > .
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage: http://www.absoft.com.vn
> 
> *
> *
> *

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Ừ nhỉ. Đúng là giật mình cái không đâu! :D

**Comment by lotuong** [comment]
Done!
