### ISSUE TITLE
Thêm trường email và số điện thoại di động của Đoàn viên

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#67]
Để tiện tra cứu khi cần liên lạc, Công bố trí thêm trường Email và Số điện thoại của Đoàn viên trong form thêm mới Đoàn viên nhé. 

Từ dữ liệu đó có thể xây dựng thêm báo cáo: Danh sách liên lạc cán bộ đoàn toàn hệ thống. :)

**Comment by dukec2020** [comment]
Đã thêm email và mobile.

2013/8/19 lotuong notifications@github.com

> Để tiện tra cứu khi cần liên lạc, Công bố trí thêm trường Email và Số điện
> thoại của Đoàn viên trong form thêm mới Đoàn viên nhé.
> 
> Từ dữ liệu đó có thể xây dựng thêm báo cáo: Danh sách liên lạc cán bộ đoàn
> toàn hệ thống. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/67
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
