### ISSUE TITLE
Thêm một loại user nữa

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#68]
Thêm một loại user là Test user: Được phép sử dụng các tính năng báo cáo, được xem thông tin nhưng không được phép thêm, xoá hay sửa đổi bất kỳ thông tin nào.

**Comment by dukec2020** [comment]
Done:
username: test
pass: test

2013/8/21 lotuong notifications@github.com

> Thêm một loại user là Test user: Được phép sử dụng các tính năng báo cáo,
> được xem thông tin nhưng không được phép thêm, xoá hay sửa đổi bất kỳ thông
> tin nào.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/68
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
