### ISSUE TITLE
Lỗi mất quyền quản trị cấp cao khi đổi mật khẩu

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#69]
Một số chi đoàn sau khi thực hiện đổi mật khẩu theo hướng dẫn thì quyền Chi đoàn bị đổi thành quyền Đoàn viên, dẫn đến có nhiều tính năng không thực hiện được, vd như nhập sự kiện mới của chi đoàn. 

Em xem lại giúp anh lỗi này nha.

**Comment by dukec2020** [comment]
Done

2013/8/26 lotuong notifications@github.com

> Một số chi đoàn sau khi thực hiện đổi mật khẩu theo hướng dẫn thì quyền
> Chi đoàn bị đổi thành quyền Đoàn viên, dẫn đến có nhiều tính năng không
> thực hiện được, vd như nhập sự kiện mới của chi đoàn.
> 
> Em xem lại giúp anh lỗi này nha.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/69
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
