### ISSUE TITLE
Lỗi phần mềm: Mục theo dõi chi đoàn & Theo dõi cá nhân

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#7]
Sau khi xoá toàn bộ các hoạt động của Đoàn cơ sở và của các chi đoàn đi để nhập lại thì các mục Theo dõi chi đoàn và Theo dõi cá nhân hiện thông báo lỗi: "Trying to get property of none object"

**Comment by dukec2020** [comment]
Cái này là do khi xóa sự kiện đi thì các bản ghi chấm điểm bị "mồ côi" do mất dữ liệu sự kiện, hiện em chưa cho xóa đệ quy (xóa cha thì xóa con), làm cái này khá nguy hiểm. Có thể là giờ muốn xóa thì kiểm tra nó có con, bắt phải xóa con trước nhỉ.

**Comment by dukec2020** [comment]
Hiện em đã tạm khắc phục bằng cách xóa dữ liệu bị mồ côi đi. Em sẽ bổ sung tính năng kiểm tra dữ liệu khi xóa sau.

**Comment by lotuong** [comment]
Đã được xử lý!
