### ISSUE TITLE
Thống kê số lượng cán bộ đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#70]
Chi đoàn Giám sát tín dụng đề nghị kiểm tra lại xem tại sao chi đoàn họ có 10 đoàn viên mà thống kê lại ra có tận 10 cán bộ đoàn. Chỉ có các đoàn viên có chức danh mới được tính là cán bộ đoàn thôi. Như vậy số cán bộ đoàn đúng ra chỉ có 4: Hiệp, Trung, Thịnh & Hùng 
![thong ke so lieu](https://f.cloud.github.com/assets/1740657/1078033/2fafd7c8-1518-11e3-9d98-ae0a64704e67.JPG)

**Comment by dukec2020** [comment]
Done.
