### ISSUE TITLE
Lẫn sự kiện của chi đoàn vào danh sách sự kiện của Đoàn cơ sở

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#72]
Khi anh bấm vào Sự kiện Đoàn cơ sở trong phần CHỨC NĂNG, sao vẫn hiện ra một số sự kiện của chi đoàn Châu Văn Liêm - Cần Thơ nhỉ? Em xem lại giúp anh để chỉ hiện ra các sự kiện của Đoàn cơ sở thôi nhé. Không hiện sự kiện riêng của các chi đoàn.

**Comment by dukec2020** [comment]
Anh cho em thông tin user đăng nhập anh dùng, và sự kiện bị lẫn anh nhé,
nhiều khả năng là do thông tin sự kiện không chính xác.

2013/9/4 lotuong notifications@github.com

> Khi anh bấm vào Sự kiện Đoàn cơ sở trong phần CHỨC NĂNG, sao vẫn hiện ra
> một số sự kiện của chi đoàn Châu Văn Liêm - Cần Thơ nhỉ? Em xem lại giúp
> anh để chỉ hiện ra các sự kiện của Đoàn cơ sở thôi nhé. Không hiện sự kiện
> riêng của các chi đoàn.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/72
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
anh dùng user pvfc thôi. Đã kiểm tra mấy sự kiện "Cần Thơ" ấy rồi và thấy là nhập đúng yêu cầu.
Hoặc mình thử tạo thêm 1 user cấp Chi đoàn của chi đoàn Châu Văn Liêm và nhập thêm 1 sự kiện cấp chi đoàn trong tháng 7 là rõ ngay

**Comment by dukec2020** [comment]
em vừa tạo user: test1 của CVL,
Tạo sk tên là : "Test sk cvl" do CVL làm đầu mối,
Vào user pvfc và admin đều ko thấy nó hiện mà anh?

2013/9/4 lotuong notifications@github.com

> anh dùng user pvfc thôi. Đã kiểm tra mấy sự kiện "Cần Thơ" ấy rồi và thấy
> là nhập đúng yêu cầu.
> Hoặc mình thử tạo thêm 1 user cấp Chi đoàn của chi đoàn Châu Văn Liêm và
> nhập thêm 1 sự kiện cấp chi đoàn trong tháng 7 là rõ ngay
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/72#issuecomment-23776949
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Anh phát hiện ra là làm sao rồi. Đây là do lỗi bị giáng cấp quyền quản trị từ đợt trước nên riêng chi nhánh Cần Thơ bị lỗi này thôi. Sau khi sửa sự kiện thành sự kiện do chi đoàn Châu Văn Liêm làm đầu mối thì mọi thứ đã OK. 

Giờ chỉ còn phải xem lại xem có sự kiện nào trùng để xoá bớt.

**Comment by lotuong** [comment]
Anh xoá luôn mấy sự kiện test của em rồi nhé! :)
