### ISSUE TITLE
Thay đổi giá trị mặc định trong BC Hoạt động chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#73]
Khi truy cập từ account chi đoàn, nên cố định trường Chi đoàn là chi đoàn đang đăng nhập. Không cho phép xem & xuất báo cáo của các chi đoàn khác vì đã có thể làm được điều này ở mục Chấm điểm chi đoàn rồi. 
![bc chi doan](https://f.cloud.github.com/assets/1740657/1086335/b4a88f2e-15f9-11e3-827d-c0c53c96f293.JPG)

**Comment by lotuong** [comment]
Báo cáo hoạt động của Đoàn cơ sở có nên mở ra cho các chi đoàn dùng không nhỉ? Anh thấy có lẽ không cần lắm!

**Comment by dukec2020** [comment]
Done

2013/9/5 lotuong notifications@github.com

> Báo cáo hoạt động của Đoàn cơ sở có nên mở ra cho các chi đoàn dùng không
> nhỉ? Anh thấy có lẽ không cần lắm!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/73#issuecomment-23853010
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Ngon hơn dự kiến! ^_^
