### ISSUE TITLE
Phân quyền đối với Báo cáo kết quả hoạt động cá nhân

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#74]
Hiện tại khi truy cập bằng account chi đoàn, phần mềm cho phép xuất báo cáo hoạt động cá nhân của đoàn viên chi đoàn khác. Cần hạn chế chỉ được in báo cáo hoạt động của một hoặc các cá nhân thuộc chi đoàn mình.

**Comment by dukec2020** [comment]
Done

2013/9/5 lotuong notifications@github.com

> Hiện tại khi truy cập bằng account chi đoàn, phần mềm cho phép xuất báo
> cáo hoạt động cá nhân của đoàn viên chi đoàn khác. Cần hạn chế chỉ được in
> báo cáo hoạt động của một hoặc các cá nhân thuộc chi đoàn mình.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/74
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
