### ISSUE TITLE
Không tính những đoàn viên đã bỏ kích hoạt vào tổng số đoàn viên

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#75]
Chi đoàn Thẩm định báo lại là mặc dù họ đã cho 1 đồng chí trưởng thành đoàn nhưng vẫn bị tính vào tổng số đoàn viên. Em xem lại giúp anh các trường hợp tương tự nhé.

**Comment by dukec2020** [comment]
Căn cứ vào thuộc tính  "kích hoạt" hay thuộc tính "đoàn viên" để xem 1
người là đv hay ko anh nhỉ?

2013/9/5 lotuong notifications@github.com

> Chi đoàn Thẩm định báo lại là mặc dù họ đã cho 1 đồng chí trưởng thành
> đoàn nhưng vẫn bị tính vào tổng số đoàn viên. Em xem lại giúp anh các
> trường hợp tương tự nhé.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/75
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Em đã bỏ các điều kiện tính, không cộng các user bỏ kích hoạt rồi anh nhé,
lẽ ra nên dùng thuộc tính là đoàn viên hay không thì có vẻ hợp lý hơn.

2013/9/5 Hoàng Văn Công hvcong@gmail.com

> Căn cứ vào thuộc tính  "kích hoạt" hay thuộc tính "đoàn viên" để xem 1
> người là đv hay ko anh nhỉ?
> 
> 2013/9/5 lotuong notifications@github.com
> 
> > Chi đoàn Thẩm định báo lại là mặc dù họ đã cho 1 đồng chí trưởng thành
> > đoàn nhưng vẫn bị tính vào tổng số đoàn viên. Em xem lại giúp anh các
> > trường hợp tương tự nhé.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/75
> > .
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage: http://www.absoft.com.vn
> 
> *
> *
> *

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Ờ nhỉ. Hay dùng cả 2 đi! Nếu thiếu 1 trong hai thì không phải Đoàn viên! :)

**Comment by lotuong** [comment]
Cái này xong chưa Công nhỉ?

**Comment by dukec2020** [comment]
Xong rồi anh ạ.

On Sat, Oct 19, 2013 at 3:18 PM, lotuong notifications@github.com wrote:

> Cái này xong chưa Công nhỉ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/75#issuecomment-26645869
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
