### ISSUE TITLE
Chấm điểm cá nhân chỉ thể hiện tổng điểm, không thể hiện từng hoạt động

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#76]
Hiện tại mục chấm điểm cá nhân liệt kê từng hoạt động mà mỗi cá nhân ở các chi đoàn thực hiện. Để cho gọn và thông tin có ý nghĩa sử dụng hơn thì  nên tổng hợp lại giống như trong báo cáo hoạt động cá nhân (của một chi đoàn), nghĩa là thể hiện DANH SÁCH ĐOÀN VIÊN CHI ĐOÀN KÈM THEO ĐIỂM THI ĐUA CỦA TỪNG ĐOÀN VIÊN TRONG KỲ BÁO CÁO. 
Mẫu báo cáo có rồi nên chắc em chuyển sang form sẽ đỡ mất thời gian hơn.

**Comment by dukec2020** [comment]
Anh mô tả rõ hơn, em chưa hiểu ý anh lắm.

2013/9/5 lotuong notifications@github.com

> Hiện tại mục chấm điểm cá nhân liệt kê từng hoạt động mà mỗi cá nhân ở các
> chi đoàn thực hiện. Để cho gọn và thông tin có ý nghĩa sử dụng hơn thì nên
> tổng hợp lại giống như trong báo cáo hoạt động cá nhân (của một chi đoàn),
> nghĩa là thể hiện DANH SÁCH ĐOÀN VIÊN CHI ĐOÀN KÈM THEO ĐIỂM THI ĐUA CỦA
> TỪNG ĐOÀN VIÊN TRONG KỲ BÁO CÁO.
> Mẫu báo cáo có rồi nên chắc em chuyển sang form sẽ đỡ mất thời gian hơn.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/76
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Hiện tại nó như thế này:
![cham diem doan vien](https://f.cloud.github.com/assets/1740657/1094072/3a4b1c46-16bd-11e3-82ae-a322298b7bb8.JPG)

Anh muốn nó như thế này, vì thông tin này để mở để các chi đoàn xem được của nhau nên chỉ cần biết ai được bao nhiêu điểm thôi, chứ không cần biết ai đã làm gì. 
![bao cao chi doan](https://f.cloud.github.com/assets/1740657/1094078/63c8d298-16bd-11e3-9fc4-688ff32081dd.JPG)

Thông tin chi tiết như thế này thì chỉ chi đoàn nào biết chi đoàn đó (Cái này vừa sửa được rồi)
![bao cao ca nhan](https://f.cloud.github.com/assets/1740657/1094081/80cbb18a-16bd-11e3-938c-40c0b6d87628.JPG)

**Comment by dukec2020** [comment]
Vậy thì chỉ cần bỏ tính năng ở cái ảnh 1 đi là xong thôi anh nhỉ?

2013/9/6 lotuong notifications@github.com

> Hiện tại nó như thế này:
> [image: cham diem doan vien]https://f.cloud.github.com/assets/1740657/1094072/3a4b1c46-16bd-11e3-82ae-a322298b7bb8.JPG
> 
> Anh muốn nó như thế này, vì thông tin này để mở để các chi đoàn xem được
> của nhau nên chỉ cần biết ai được bao nhiêu điểm thôi, chứ không cần biết
> ai đã làm gì.
> [image: bao cao chi doan]https://f.cloud.github.com/assets/1740657/1094078/63c8d298-16bd-11e3-9fc4-688ff32081dd.JPG
> 
> Thông tin chi tiết như thế này thì chỉ chi đoàn nào biết chi đoàn đó (Cái
> này vừa sửa được rồi)
> [image: bao cao ca nhan]https://f.cloud.github.com/assets/1740657/1094081/80cbb18a-16bd-11e3-938c-40c0b6d87628.JPG
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/76#issuecomment-23921326
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Hơi lăn tăn. Đúng là có sự trùng lặp. Tuy nhiên anh vẫn muốn giữ vì: 
- Form ở hình 1 trực quan và nhanh chóng hơn. Xem được tất cả các chi đoàn cùng lúc trong khi báo cáo ở hình 2 thì chi đoàn nào xem được của chi đoàn đó thôi. Lại phải bấm nút mới ra được báo cáo. 
- Các chi đoàn xem báo cáo ở hình 1 sẽ nhanh chóng xác định được các thành viên tích cực nhất và có sự thi đua với nhau trong hoạt động. Đồng thời những người không bao giờ tham gia hoạt động gì cũng sẽ lộ ra ngay. Vậy thì Đoàn cơ sở sẽ có lý do công khai trong việc nhận xét các trường hợp xét kết nạp đảng, chuyển đảng chính thức...

**Comment by lotuong** [comment]
Done!
