### ISSUE TITLE
Sự kiện không được tự động trình duyệt

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#77]
Các chi đoàn Nguyễn Viết Xuân (14), Mỹ Khê (1), PSI (1), Châu Văn Liêm (2), Đầu tư (1), Trần Phú (1) đã nhập các hoạt động của họ trong Quý III. Xem ở phần Sự kiện chi đoàn thì thấy đầy đủ. Nhưng vào phần theo dõi chi đoàn để duyệt điểm thì không thấy các sự kiện đó đâu để mà duyệt. 

Lỗi này xảy ra ở nhiều chi đoàn nên anh chắc là do lỗi phần mềm. Nhưng khi thử xoá sự kiện của chi đoàn đi và nhập lại sự kiện từ máy của anh thì lại OK. Không biết là sai ở đâu nữa. 

Để tối về nhà thử dùng trình duyệt khác xem kết quả như thế nào. Lỗi này nghiêm trọng, nếu không khắc phục thì không tiếp tục hướng dẫn các chi đoàn được!!!

![s kin qiii](https://f.cloud.github.com/assets/1740657/1087153/cc416f46-160f-11e3-851b-137bcdabd0ab.JPG)

**Comment by lotuong** [comment]
Test o nha voi chi doan QTRR khong thay co van de gi. 
Em test 1 phat voi chi doan Tran Phu xem ntn! :)

**Comment by dukec2020** [comment]
Em vừa tạo thử 1 sk của Trần Phú, thấy vẫn ok!

2013/9/5 lotuong notifications@github.com

> Test o nha voi chi doan QTRR khong thay co van de gi.
> Em test 1 phat voi chi doan Tran Phu xem ntn! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/77#issuecomment-23871138
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Anh có tạo một số sự kiện test của chi đoàn QTRR. Sau đó xoá đi. Khi nhìn vào bảng Theo dõi chi đoàn thì thấy đã xoá rồi nhưng ở bảng Sự kiện chi đoàn thì vẫn còn, không xoá được. Em kiểm tra giúp anh với!

**Comment by lotuong** [comment]
Cái này có vẻ như không xảy ra nữa. Tạm tắt đi đã, nếu bị lại thì sẽ sửa sau!
