### ISSUE TITLE
Bổ sung tham số Vùng của các chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#78]
Hiện tại tham số về Vùng đã có: 
Miền Bắc / Miền Trung / Miền Nam / Miền Tây Nam Bộ

Theo phân vùng mới của PVcomBank, sẽ có các vùng là:
Hội sở / Miền Bắc / Miền Trung / Miền Đông Nam Bộ / Miền Tây Nam Bộ. 

Vậy cần thêm vùng "Hội sở" và sửa "Miền Nam" thành "Miền Đông Nam Bộ".

Dự kiến sẽ thành lập mới các chi đoàn tại các chi nhánh WTB cũ trong Quý IV/2013

**Comment by dukec2020** [comment]
done

2013/10/15 lotuong notifications@github.com

> Hiện tại tham số về Vùng đã có:
> Miền Bắc / Miền Trung / Miền Nam / Miền Tây Nam Bộ
> 
> Theo phân vùng mới của PVcomBank, sẽ có các vùng là:
> Hội sở / Miền Bắc / Miền Trung / Miền Đông Nam Bộ / Miền Tây Nam Bộ.
> 
> Vậy cần thêm vùng "Hội sở" và sửa "Miền Nam" thành "Miền Đông Nam Bộ".
> 
> Dự kiến sẽ thành lập mới các chi đoàn tại các chi nhánh WTB cũ trong Quý
> IV/2013
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/78
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
