### ISSUE TITLE
Nội dung drop down menu trong phần Theo dõi chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#79]
Khi sử dụng account của Đoàn cơ sở để đánh giá các chi đoàn về việc tham gia các hoạt động do Đoàn cơ sở tổ chức, danh sách các sự kiện hiện ra tại menu đổ xuống bao gồm cả các sự kiện do chi đoàn tự tổ chức. Việc này gây bất tiện cho quá trình chọn sự kiện. Cần lọc bỏ chỉ để lại các sự kiện do BCH Đoàn cơ sở tổ chức mà thôi.

**Comment by lotuong** [comment]
Không xoá được sự kiện 171 và sự kiện 173

**Comment by dukec2020** [comment]
Là do anh dùng tài khoản không đủ thẩm quyền. em dùng admin thì xóa được rồi

2013/10/15 lotuong notifications@github.com

> Không xoá được sự kiện 171 và sự kiện 173
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/79#issuecomment-26319178
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Cái này khi nào có tgian em sẽ làm, đợt này bận quá.

2013/10/15 lotuong notifications@github.com

> Khi sử dụng account của Đoàn cơ sở để đánh giá các chi đoàn về việc tham
> gia các hoạt động do Đoàn cơ sở tổ chức, danh sách các sự kiện hiện ra tại
> menu đổ xuống bao gồm cả các sự kiện do chi đoàn tự tổ chức và các sự kiện
> của Đoàn cơ sở nhưng đã bị xoá. Việc này gây bất tiện cho quá trình chọn sự
> kiện. Cần lọc bỏ chỉ để lại các sự kiện do BCH Đoàn cơ sở tổ chức mà thôi.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/79
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Ok! Anh viết vào cho khỏi quên!

**Comment by lotuong** [comment]
Không cần lọc nữa nhé. Để chấm điểm trường hợp một chi đoàn tham gia vào sự kiện do một chi đoàn khác tổ chức! :)
