### ISSUE TITLE
Trùng lặp giữa Sự kiện Đoàn cơ sở và Sự kiện Chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#8]
Hai mục này khi nhập mới sự kiện thì giống hệt nhau. Nếu để là sự kiện đoàn cơ sở thì mục Đầu mối bỏ trống. Nếu có nhập thì là thành ra Sự kiện chi đoàn. Nên phát sinh trùng lặp.

Nên sửa lại form nhập liệu của Sự kiện Đoàn cơ sở -> Bỏ bớt trường Đầu mối đi cho đỡ lẫn lộn.

**Comment by lotuong** [comment]
Trong phần list các sự kiện cũng thế. Danh sách các sự kiện của Đoàn cơ sở thì đương nhiên đầu mối được hiểu là Đoàn cơ sở rồi. Không cần phải thêm cột đó nữa.

**Comment by dukec2020** [comment]
2 trường hợp này em chung 1 form, mục đích của cái đầu mối thì đúng như anh nói đó, nếu mình quy định cách nhập thì sẽ không bị nhầm. Đối với user quyền là chi đoàn thì chỉ được chọn đầu mối là chi đoàn đó.
Cái này nếu cần thiết thì em sẽ tạo thêm tính năng, nhưng em thấy cũng không cần lắm :)

**Comment by dukec2020** [comment]
Em đã bỏ cột đầu mối tại list trường hợp là danh sách sk đoàn cs.

**Comment by lotuong** [comment]
Uh, cái này chỉ liên quan đến ông Đoàn cơ sở thôi nên cũng ko cần lắm. Thanks em!
