### ISSUE TITLE
Không duyệt được điểm cho các chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#81]
Khi click vào chữ Chưa duyệt (màu vàng) không hiện ra hộp thoại cho phép duyệt - Trang web tự động chuyển về đầu trang và không có gì xảy ra cả. VD: Các hoạt động số 656, 676, 697

Xem gấp giúp anh với nhé.

**Comment by dukec2020** [comment]
anh dùng user quyền gì?

2013/10/16 lotuong notifications@github.com

> Khi click vào chữ Chưa duyệt (màu vàng) không hiện ra hộp thoại cho phép
> duyệt - Trang web tự động chuyển về đầu trang và không có gì xảy ra cả. VD:
> Các hoạt động số 656, 676, 697
> 
> Xem gấp giúp anh với nhé.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/81
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Đoàn cơ sở! account pvfc

**Comment by dukec2020** [comment]
đúng là bị khi tìm kiếm và sửa kết quả tìm kiếm.
Nếu sửa trực tiếp cái có sẵn thì không sao.

On Wed, Oct 16, 2013 at 3:34 PM, lotuong notifications@github.com wrote:

> Đoàn cơ sở! account pvfc
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/81#issuecomment-26400931
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Navigate đến các trang sau để sửa cũng ko được

**Comment by lotuong** [comment]
Tạm thời có thể khắc phục bằng cách xoá các trình duyệt không duyệt được đi để nhập lại. Cái này có khi lại tốt, bắt buộc phải duyệt cho nhanh kẻo nó sang trang sau thì không sửa được. :)

**Comment by dukec2020** [comment]
đơn giản chỉ cần nhấn vào edit và thay đổi giá trị duyệt là được mà anh.

2013/10/17 lotuong notifications@github.com

> Tạm thời có thể khắc phục bằng cách xoá các trình duyệt không duyệt được
> đi để nhập lại.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/81#issuecomment-26489172
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Hôm nay em sửa mãi mà chưa được cái lỗi này, lỗi khó chịu thật.

2013/10/17 Hoàng Văn Công hvcong@gmail.com

> đơn giản chỉ cần nhấn vào edit và thay đổi giá trị duyệt là được mà anh.
> 
> 2013/10/17 lotuong notifications@github.com
> 
> > Tạm thời có thể khắc phục bằng cách xoá các trình duyệt không duyệt được
> > đi để nhập lại.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/81#issuecomment-26489172
> > .
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage: http://www.absoft.com.vn
> 
> *
> *
> *

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by dukec2020** [comment]
Phù, xong rồi anh ạ,
Trời mát làm việc hiệu quả hơn, giờ cái chức năng này trông có vẻ xịn hơn
nhiều :)

2013/10/17 Hoàng Văn Công hvcong@gmail.com

> Hôm nay em sửa mãi mà chưa được cái lỗi này, lỗi khó chịu thật.
> 
> 2013/10/17 Hoàng Văn Công hvcong@gmail.com
> 
> > đơn giản chỉ cần nhấn vào edit và thay đổi giá trị duyệt là được mà anh.
> > 
> > 2013/10/17 lotuong notifications@github.com
> > 
> > > Tạm thời có thể khắc phục bằng cách xoá các trình duyệt không duyệt được
> > > đi để nhập lại.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/81#issuecomment-26489172
> > > .
> > 
> > ## 
> > 
> > *
> > 
> > ---
> > 
> > Mr. Hoàng Văn Công
> > 
> > An Bien Software Innovation Company
> > 
> > Hải Phòng City, Vietnam
> > *
> > _Mobile: (+84) 902076788
> > *_
> > 
> > Homepage: http://www.absoft.com.vn
> > 
> > *
> > *
> > *
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage: http://www.absoft.com.vn
> 
> *
> *
> *

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Ngon rồi! Gud Gud!!!
