### ISSUE TITLE
lỗi phần chấm điểm cá nhân

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#82]
Khi  bấm vào CHỨC NĂNG - THEO DÕI CÁ NHÂN thì toàn thấy code hiện ra.

**Comment by dukec2020** [comment]
Lỗi này là do ai đó xóa 1 đoàn viên đi anh ạ.
Co lẽ giờ không cho xóa nữa mà chỉ cho ẩn đi thôi!.

2013/10/17 lotuong notifications@github.com

> Khi bấm vào CHỨC NĂNG - THEO DÕI CÁ NHÂN thì toàn thấy code hiện ra.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/82
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
OK, em chỉ cho phép thêm, không xoá nhé. Bạn nào chuyển đi thì bỏ chỗ Kích hoạt ra thôi.

**Comment by dukec2020** [comment]
Done

On Sat, Oct 19, 2013 at 1:15 PM, lotuong notifications@github.com wrote:

> OK, em chỉ cho phép thêm, không xoá nhé. Bạn nào chuyển đi thì bỏ chỗ Kích
> hoạt ra thôi.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/82#issuecomment-26644343
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*
