### ISSUE TITLE
Lỗi báo cáo - tính tổng điểm sai

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#83]
Khi tính điểm quý III/2013 ở phần CHẤM ĐIỂM, CHẤM ĐIỂM CHI ĐOÀN, chi đoàn Tô Vĩnh Diện chỉ được 46 điểm. 

Nhưng khi in Bảng điểm tổng hợp ở mục Báo cáo - Hoạt động chi đoàn thì số điểm lên tới 71

**Comment by dukec2020** [comment]
Em đếm đủ 71 điểm mà anh?

2013/10/17 lotuong notifications@github.com

> Khi tính điểm quý III/2013 ở phần CHẤM ĐIỂM, CHẤM ĐIỂM CHI ĐOÀN, chi đoàn
> Tô Vĩnh Diện chỉ được 46 điểm.
> 
> Nhưng khi in Bảng điểm tổng hợp ở mục Báo cáo - Hoạt động chi đoàn thì số
> điểm lên tới 71
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/83
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
OK, bây giờ lại ngon rồi!
