### ISSUE TITLE
Đoàn cơ sở có thể chấm điểm thay cho chi đoàn được không?

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#84]
Đoàn cơ sở có thể tạo mới một sự kiện do chi đoàn làm đầu mối được không nhỉ?
Anh thử tạo một sự kiện "giúp" chi đoàn KTNB như trong hình. 
![ktnb](https://f.cloud.github.com/assets/1740657/1351057/858a46d4-3718-11e3-99af-d0f6c1e2845f.PNG)

Tuy nhiên khi truy cập bằng account Đoàn cơ sở thì sự kiện này biến mất không để lại đấu vết luôn. Các sự kiện 199, 200, 202, 203 cũng không thấy xuất hiện. Có thể là vì anh dùng account của Đoàn cơ sở xoá mất các sự kiện này rồi nhưng vào bằng account của chi đoàn vẫn thấy nguyên xi. Em kiểm tra lại giúp anh nhé.

**Comment by lotuong** [comment]
Một số chi đoàn khác như Đặng Thuỳ Trâm cũng có hiện tượng này

**Comment by dukec2020** [comment]
Đoàn CS vẫn có thể tạo được luôn, nhưng không tự động tạo dữ liệu chấm
điểm, sau khi tạo phải vào tạo chấm điểm nữa thì mới có anh ạ.

2013/10/17 lotuong notifications@github.com

> Đoàn cơ sở có thể tạo mới một sự kiện do chi đoàn làm đầu mối được không
> nhỉ?
> Anh thử tạo một sự kiện "giúp" chi đoàn KTNB như trong hình.
> [image: ktnb]https://f.cloud.github.com/assets/1740657/1351057/858a46d4-3718-11e3-99af-d0f6c1e2845f.PNG
> Tuy nhiên khi truy cập bằng account Đoàn cơ sở thì sự kiện này biến mất
> không để lại đấu vết luôn.
> 
> Các chi đoàn cũng không tự xoá được các sự kiện mình đã tạo, em kiểm tra
> lại giúp anh nhé.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/84
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Cái này OK
