### ISSUE TITLE
phân quyền cho chi đoàn tự xoá sự kiện do mình khởi tạo

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#85]
Hiện các chi đoàn chưa được phân quyền để thực hiện tác vụ này

**Comment by dukec2020** [comment]
Chi Đoàn có thể xóa được, chỉ cần xóa các chấm điểm liên quan tới sự kiện
đó trước khi xóa sự kiện là được.

2013/10/17 lotuong notifications@github.com

> Hiện các chi đoàn chưa được phân quyền để thực hiện tác vụ này
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/85
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
cái này ok em nhé
