### ISSUE TITLE
Thứ tự các sự kiện trong hộp chọn sự kiện của form Thêm theo dõi chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#87]
Form Thêm theo dõi chi đoàn nằm trong phần Chức năng - Sự kiện chi đoàn. 
hiện tại đang sắp xếp theo ngày bắt đầu của sự kiện nhưng anh thấy không hợp lý lắm. Mỗi lần nhập thông tin phải kéo xuống để tìm rất mệt. 
Chi bằng sắp xếp theo ID của sự kiện để sự kiện nào mới tạo thì nằm phía trên cho dễ chọn. 
![su kien](https://f.cloud.github.com/assets/1740657/1365870/e74d8404-3898-11e3-81d6-6bb11212d233.png)

**Comment by dukec2020** [comment]
done

2013/10/19 lotuong notifications@github.com

> Form Thêm theo dõi chi đoàn nằm trong phần Chức năng - Sự kiện chi đoàn.
> hiện tại đang sắp xếp theo ngày bắt đầu của sự kiện nhưng anh thấy không
> hợp lý lắm. Mỗi lần nhập thông tin phải kéo xuống để tìm rất mệt.
> Chi bằng sắp xếp theo ID của sự kiện để sự kiện nào mới tạo thì nằm phía
> trên cho dễ chọn.
> [image: su kien]https://f.cloud.github.com/assets/1740657/1365870/e74d8404-3898-11e3-81d6-6bb11212d233.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/87
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Hình như đang bị lỗi! :)

**Comment by dukec2020** [comment]
Em up thiếu file, done.

On Sat, Oct 19, 2013 at 10:30 PM, lotuong notifications@github.com wrote:

> Hình như đang bị lỗi! :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/87#issuecomment-26651988
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
Hic, bọn mình không hiểu ý nhau rồi. Anh muốn sắp xếp cái menu đổ xuống trong form Thêm theo dõi chi đoàn thì em lại sắp xếp thứ tự bản ghi trong form Danh sách sự kiện chi đoàn. Còn cái menu đổ xuống thì vẫn y như cũ. 
![thesame](https://f.cloud.github.com/assets/1740657/1367015/89868a60-38f6-11e3-8efd-3b525bfec4ac.png)
Mặc dù vậy phần em đã làm lại thành ra rất ổn. Thế này duyệt điểm sẽ dễ hơn trước. 

Em xem lại giúp anh cái này nữa nhé:
![chon su kien](https://f.cloud.github.com/assets/1740657/1367023/f28107ca-38f6-11e3-9a10-9286bb07d391.png)
Anh muốn khi bấm vào chỗ có mũi tên đỏ thì list hiện ra sẽ có các dòng theo thứ tự: 
- Tham gia ngày hội văn hoá thể thao tại hội nghị tập huấn khu vực phía nam của Đoàn Khối
- Cập nhật email group của Đoàn thanh niên
- Tạo thư mục chia sẻ và phân quyền cho BCH Đoàn cơ sở
- Tham gia thiết kế phần mềm QLĐV
  ...

Như hiện tại, nếu muốn thêm 1 chi đoàn nữa vào sự kiện ngày hội văn hoá thể thao của đoàn khối, anh phải rà tìm xuống dòng thứ 50 của cái drop down mới thấy! >_<

**Comment by dukec2020** [comment]
Các nd a yc chỉ là một cái cụ thể của tháng này.nếu thay nó ko có hiệu quả
lâu dài anh ạ.

**Comment by dukec2020** [comment]
Anh thử tính năng chấm điểm cho chi đoàn em mới tạo xem có tiện hơn không
nhé, cái select nó bị dài quá, do nội dung của sk quá dài.

2013/10/20 Hoàng Văn Công hvcong@gmail.com

> Các nd a yc chỉ là một cái cụ thể của tháng này.nếu thay nó ko có hiệu quả
> lâu dài anh ạ.
> On Oct 20, 2013 2:50 AM, "lotuong" notifications@github.com wrote:
> 
> > Hic, bọn mình không hiểu ý nhau rồi. Anh muốn sắp xếp cái menu đổ xuống
> > trong form Thêm theo dõi chi đoàn thì em lại sắp xếp thứ tự bản ghi trong
> > form Danh sách sự kiện chi đoàn. Còn cái menu đổ xuống thì vẫn y như cũ.
> > [image: thesame]https://f.cloud.github.com/assets/1740657/1367015/89868a60-38f6-11e3-8efd-3b525bfec4ac.png
> > Mặc dù vậy phần em đã làm lại thành ra rất ổn. Thế này duyệt điểm sẽ dễ
> > hơn trước.
> > 
> > Em xem lại giúp anh cái này nữa nhé:
> > [image: chon su kien]https://f.cloud.github.com/assets/1740657/1367023/f28107ca-38f6-11e3-9a10-9286bb07d391.png
> > Anh muốn khi bấm vào chỗ có mũi tên đỏ thì list hiện ra sẽ có các dòng
> > theo thứ tự:
> > - Tham gia ngày hội văn hoá thể thao tại hội nghị tập huấn khu vực
> >   phía nam của Đoàn Khối
> > - Cập nhật email group của Đoàn thanh niên
> > - Tạo thư mục chia sẻ và phân quyền cho BCH Đoàn cơ sở
> > - Tham gia thiết kế phần mềm QLĐV ...
> > 
> > Như hiện tại, nếu muốn thêm 1 chi đoàn nữa vào sự kiện ngày hội văn hoá
> > thể thao của đoàn khối, anh phải rà tìm xuống dòng thứ 50 của cái drop down
> > mới thấy! >_<
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/87#issuecomment-26657512
> > .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage: http://www.absoft.com.vn

*
*
*

**Comment by lotuong** [comment]
OK phần thứ tự. Để dùng thêm một thời gian nữa xem như thế nào đã.

Bố trí form chấm điểm mới hợp lý hơn trước. Nhưng kích thước hơi bị vượt khung. Phần đó mình không khuyến khích các chi đoàn viết nhiều. Chỉ là cái tên thôi, còn các nội dung khác như kết quả, ý nghĩa thì phải đưa vào phần mô tả sự kiện. Nên em cứ cho độ rộng ô ngắn lại giúp anh, giới hạn để không phá vỡ form THÊM THEO DÕI CHI ĐOÀN

(tên dài hay ngắn cũng vẫn chấm điểm được mà!) :)
