### ISSUE TITLE
Thêm trường thông tin cho BÁO CÁO - Bảng điểm chi đoàn

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#88]
Ở Bảng điểm của chi đoàn Nguyễn Viết Xuân
![bang diem chi doan](https://f.cloud.github.com/assets/1740657/1370646/69290820-3a26-11e3-92f8-ccba92d7796c.PNG)

Anh muốn xem thêm phần mô tả sự kiện của hoạt động riêng số 1 nhưng không có cách nào. Các chức năng khác của phần mềm cũng không cho phép. Nên em xem có thể bổ sung 1 cột nữa là Mô tả sự kiện vào Báo cáo này không nhé. 

Ngoài ra hoạt động riêng số 1 (Giải bóng đã tập đoàn DKVN) cũng có ngày kết thúc trước cả ngày bắt đầu. Nên có biện pháp kiểm soát để lỗi này không xảy ra.

**Comment by lotuong** [comment]
Note: Tính điểm đề xuất ý tưởng cho chi nhánh Thăng Long

**Comment by dukec2020** [comment]
Done

2013/10/24 lotuong notifications@github.com

> Note: Tính điểm đề xuất ý tưởng cho chi nhánh Thăng Long
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/88#issuecomment-26964117
> .

## 

_-----------------------------------------------------------------------------------------------------------------------------Mr.
Hoàng Văn CôngAn Bien Software Innovation Company Hải Phòng City, Vietnam_

_Mobile: (+84) 902076788_

_Homepage: http://www.absoft.com.vn
http://www.absoft.com.vn/http://hoster.vn http://hoster.vn/_

**Comment by lotuong** [comment]
Sửa tương tự cho Báo cáo - Hoạt động chi đoàn - Báo cáo hoạt động Đoàn CS được không em?. Và cho độ rộng của cột Mô tả lớn hơn một chút nữa.

**Comment by dukec2020** [comment]
ok anh.

2013/11/6 lotuong notifications@github.com

> Sửa tương tự cho Báo cáo - Hoạt động chi đoàn - Báo cáo hoạt động Đoàn CS
> được không em?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/88#issuecomment-27852376
> .

## 

_-----------------------------------------------------------------------------------------------------------------------------Mr.
Hoàng Văn CôngAn Bien Software Innovation Company Hải Phòng City, Vietnam_

_Mobile: (+84) 902076788_

_Homepage: http://www.absoft.com.vn
http://www.absoft.com.vn/http://hoster.vn http://hoster.vn/_

**Comment by dukec2020** [comment]
Done

2013/11/6 Hoàng Văn Công hvcong@gmail.com

> ok anh.
> 
> 2013/11/6 lotuong notifications@github.com
> 
> > Sửa tương tự cho Báo cáo - Hoạt động chi đoàn - Báo cáo hoạt động Đoàn CS
> > được không em?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/88#issuecomment-27852376
> > .
> 
> ## 
> 
> _-----------------------------------------------------------------------------------------------------------------------------
> Mr. Hoàng Văn CôngAn Bien Software Innovation Company  Hải Phòng City,
> Vietnam_
> 
> *Mobile: (+84) 902076788 <%28%2B84%29%20902076788> *
> 
> *Homepage: http://www.absoft.com.vn http://www.absoft.com.vn/
> http://hoster.vn http://hoster.vn/ *

## 

_-----------------------------------------------------------------------------------------------------------------------------Mr.
Hoàng Văn CôngAn Bien Software Innovation Company Hải Phòng City, Vietnam_

_Mobile: (+84) 902076788_

_Homepage: http://www.absoft.com.vn
http://www.absoft.com.vn/http://hoster.vn http://hoster.vn/_
