### ISSUE TITLE
Thông báo của đoàn cơ sở trên trang chủ phần mềm

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#89]
Anh muốn có một mục thông báo ngắn gọn của BCH Đoàn cơ sở tới cho các chi đoàn để khi họ truy cập vào phần mềm thì sẽ được đọc luôn. Ví dụ như:

Ngày 18/10: BCH Đoàn cơ sở thông báo Các chi đoàn có đoàn viên tham gia xác minh học bổng sẽ được cộng điểm thi đua trong quý IV/2013. Đề nghị các chi đoàn báo cáo hoạt động qua phần mềm.

Ngày 17/10: Hạn cuối nhập thông tin vào phần mềm để tính điểm thi đua Quý III là 14h00 ngày 22/10. Các chi đoàn không phải nộp báo cáo quý III. Mỗi chi đoàn gửi đề xuất khen thưởng 3 đoàn viên xuất sắc (có thành tích kèm theo) về email phongtm@pvcombank.com trước hạn chót.

...

Các tin ngắn này được lưu lại để các chi đoàn có thể xem lại.

Em xem giúp anh nên làm thế nào cho tiện và đẹp nhé!

**Comment by dukec2020** [comment]
Được anh, em sẽ cho thiết kế dần, mấy hnay đang hơi bận chút :)

2013/10/22 lotuong notifications@github.com

> Anh muốn có một mục thông báo ngắn gọn của BCH Đoàn cơ sở tới cho các chi
> đoàn để khi họ truy cập vào phần mềm thì sẽ được đọc luôn. Ví dụ như:
> 
> Ngày 18/10: BCH Đoàn cơ sở thông báo Các chi đoàn có đoàn viên tham gia
> xác minh học bổng sẽ được cộng điểm thi đua trong quý IV/2013. Đề nghị các
> chi đoàn báo cáo hoạt động qua phần mềm.
> 
> Ngày 17/10: Hạn cuối nhập thông tin vào phần mềm để tính điểm thi đua Quý
> III là 14h00 ngày 22/10. Các chi đoàn không phải nộp báo cáo quý III. Mỗi
> chi đoàn gửi đề xuất khen thưởng 3 đoàn viên xuất sắc (có thành tích kèm
> theo) về email phongtm@pvcombank.com trước hạn chót.
> 
> ...
> 
> Các tin ngắn này được lưu lại để các chi đoàn có thể xem lại.
> 
> Em xem giúp anh nên làm thế nào cho tiện và đẹp nhé!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/89
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage:

http://www.absoft.com.vn

http://hoster.vn

*
*
*

**Comment by dukec2020** [comment]
Em đã bổ sung tính năng này.
Để tạo thông báo anh vào tạo ở menu hệ thống bên trái.
Thông báo sẽ được hiện ra ở trang chủ, theo thứ tự từ mới nhất.
Danh sách thông báo dài quá sẽ tự có scrollbar, lăn bằng chuột .

2013/10/22 Hoàng Văn Công hvcong@gmail.com

> Được anh, em sẽ cho thiết kế dần, mấy hnay đang hơi bận chút :)
> 
> 2013/10/22 lotuong notifications@github.com
> 
> > Anh muốn có một mục thông báo ngắn gọn của BCH Đoàn cơ sở tới cho các chi
> > đoàn để khi họ truy cập vào phần mềm thì sẽ được đọc luôn. Ví dụ như:
> > 
> > Ngày 18/10: BCH Đoàn cơ sở thông báo Các chi đoàn có đoàn viên tham gia
> > xác minh học bổng sẽ được cộng điểm thi đua trong quý IV/2013. Đề nghị các
> > chi đoàn báo cáo hoạt động qua phần mềm.
> > 
> > Ngày 17/10: Hạn cuối nhập thông tin vào phần mềm để tính điểm thi đua Quý
> > III là 14h00 ngày 22/10. Các chi đoàn không phải nộp báo cáo quý III. Mỗi
> > chi đoàn gửi đề xuất khen thưởng 3 đoàn viên xuất sắc (có thành tích kèm
> > theo) về email phongtm@pvcombank.com trước hạn chót.
> > 
> > ...
> > 
> > Các tin ngắn này được lưu lại để các chi đoàn có thể xem lại.
> > 
> > Em xem giúp anh nên làm thế nào cho tiện và đẹp nhé!
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/89
> > .
> 
> ## 
> 
> *
> 
> ---
> 
> Mr. Hoàng Văn Công
> 
> An Bien Software Innovation Company
> 
> Hải Phòng City, Vietnam
> *
> _Mobile: (+84) 902076788
> *_
> 
> Homepage:
> 
> http://www.absoft.com.vn
> 
> http://hoster.vn
> 
> *
> *
> *

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage:

http://www.absoft.com.vn

http://hoster.vn

*
*
*

**Comment by lotuong** [comment]
Từ tuần trước đến giờ khi nào anh ở nhà thì chỉ vào được github, không vào được phần mềm. Đến lúc đến cơ quan thì chỉ vào được phần mềm, không vào được github. Chả hiểu là tại sao! :(

**Comment by dukec2020** [comment]
A thu doỉtinh duyet khac coi.em van vao ngon: )

**Comment by lotuong** [comment]
Anh vào bằng 3G thì OK. :)
Món này ngon rồi nhé!
