### ISSUE TITLE
Đổi màu các nút bấm

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#9]
Các nút bấm: Thêm, Sửa, Xoá, Danh sách trên form, bình thường ở chế độ bóng mờ. Khi rê chuột lên mới chuyển sang màu đen đậm. Như vậy sẽ dễ khiến người dùng tưởng lầm rằng nút đó bị "đóng băng", không dùng được. 

Đề xuất đổi các nút này thành màu đen đậm, khi rê chuột lên đổi thành  màu vàng hoặc xanh đậm

**Comment by dukec2020** [comment]
Ok anh.

**Comment by dukec2020** [comment]
Done
