### ISSUE TITLE
Liệt kê danh sách nhân sự tham gia sự kiện sau khi nhập sự kiện (Của chi đoàn)

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#93]
Khi một chi đoàn nhập 1 sự kiện do họ tự tổ chức, thường họ sẽ chọn luôn những cá nhân tham gia vào sự kiện đó. Sau khi bấm nút tạo sự kiện, bảng thông tin về sự kiện sẽ hiện ra để người nhập kiểm tra lại. Bảng này chiếm 1 phần không lớn lắm ở phía trên của màn hình, phía dưới hiện để trống.

Chi đoàn PGD Ngô Quyền đề xuất khi xem thông tin về 1 sự kiện thì dưới phần thông tin về sự kiện sẽ hiện luôn danh sách những đoàn viên tham gia vào sự kiện đó, cùng với vai trò và kết quả của họ. Như vậy BCH chi đoàn có thể điều chỉnh vai trò và điểm số của đoàn viên một cách nhanh chóng và có hệ thống hơn.

**Comment by dukec2020** [comment]
done

2013/10/25 lotuong notifications@github.com

> Khi một chi đoàn nhập 1 sự kiện do họ tự tổ chức, thường họ sẽ chọn luôn
> những cá nhân tham gia vào sự kiện đó. Sau khi bấm nút tạo sự kiện, bảng
> thông tin về sự kiện sẽ hiện ra để người nhập kiểm tra lại. Bảng này chiếm
> 1 phần không lớn lắm ở phía trên của màn hình, phía dưới hiện để trống.
> 
> Chi đoàn PGD Ngô Quyền đề xuất khi xem thông tin về 1 sự kiện thì dưới
> phần thông tin về sự kiện sẽ hiện luôn danh sách những đoàn viên tham gia
> vào sự kiện đó, cùng với vai trò và kết quả của họ. Như vậy BCH chi đoàn có
> thể điều chỉnh vai trò và điểm số của đoàn viên một cách nhanh chóng và có
> hệ thống hơn.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/93
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage:

http://www.absoft.com.vn

http://hoster.vn

*
*
*
