### ISSUE TITLE
Đổi màu banner sang màu vàng

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#94]
Phần mềm chuyển từ giai đoạn thử nghiệm sang chính thức rồi nên đổi banner sang màu vàng cho nó đồng bộ với nhận dạng thương hiệu của PVcomBank Công nhé. Nếu chưa có file logo thì để anh gửi lại cho!

**Comment by dukec2020** [comment]
A chuyển cho em nhé
