### ISSUE TITLE
Sửa phân quyền mặc định của chi đoàn đối với việc phê duyệt điểm của đoàn viên khi tham gia vào sự kiện do chi đoàn tổ chức

### ISSUE THREAD

**Issue by lotuong** [lotuong/ChamdiemHD#96]
Hiện tại, để chấm điểm cho đoàn viên tham gia vào 1 hoạt động, tại form Thêm mới sự kiện, BCH Chi đoàn chọn đoàn viên từ danh sách góc dưới bên phải. Các đoàn viên được chọn sẽ được mặc định chấm điểm là: Tham gia - Tốt - Chấp thuận.

Nếu chi đoàn muốn bổ sung thêm đoàn viên vào hoạt động nêu trên => Vào mục theo dõi cá nhân. Chọn đoàn viên, chọn sự kiện (của chi đoàn), chọn vai trò, kết quả rồi bấm Thêm. Ở đây nảy xinh vấn đề là trong danh sách theo dõi đoàn viên phía dưới sẽ hiện lên 1 mục chấm điểm cho đoàn viên với trạng thái phê duyệt là Chưa duyệt. Và chi đoàn không tự duyệt được. 

Em sửa sao cho khi Chi đoàn bổ sung 1 chấm điểm cho đoàn viên tham gia vào một sự kiện đã diễn ra thì mặc định chấm điểm đó có trạng thái là phê duyệt là Chấp thuận luôn nhé. 

(Tham khảo trường hợp đoàn viên Trần Văn A của QTRR được đề xuất chấm điểm Duy trì blog sinh hoạt chuyên môn Ban QTRR - anh đã tạo làm dữ liệu test)

**Comment by dukec2020** [comment]
done.

2013/10/28 lotuong notifications@github.com

> Hiện tại, để chấm điểm cho đoàn viên tham gia vào 1 hoạt động, tại form
> Thêm mới sự kiện, BCH Chi đoàn chọn đoàn viên từ danh sách góc dưới bên
> phải. Các đoàn viên được chọn sẽ được mặc định chấm điểm là: Tham gia - Tốt
> - Chấp thuận.
> 
> Nếu chi đoàn muốn bổ sung thêm đoàn viên vào hoạt động nêu trên => Vào mục
> theo dõi cá nhân. Chọn đoàn viên, chọn sự kiện (của chi đoàn), chọn vai
> trò, kết quả rồi bấm Thêm. Ở đây nảy xinh vấn đề là trong danh sách theo
> dõi đoàn viên phía dưới sẽ hiện lên 1 mục chấm điểm cho đoàn viên với trạng
> thái phê duyệt là Chưa duyệt. Và chi đoàn không tự duyệt được.
> 
> Em sửa sao cho khi Chi đoàn bổ sung 1 chấm điểm cho đoàn viên tham gia vào
> một sự kiện đã diễn ra thì mặc định chấm điểm đó có trạng thái là phê duyệt
> là Chấp thuận luôn nhé.
> 
> (Tham khảo trường hợp đoàn viên Trần Văn A của QTRR được đề xuất chấm điểm
> Duy trì blog sinh hoạt chuyên môn Ban QTRR - anh đã tạo làm dữ liệu test)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lotuong/ChamdiemHD/issues/96
> .

## 

*

---

Mr. Hoàng Văn Công

An Bien Software Innovation Company

Hải Phòng City, Vietnam
*
_Mobile: (+84) 902076788
*_

Homepage:

http://www.absoft.com.vn

http://hoster.vn

*
*
*
